import Head from 'next/head';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ArticleComponent from '@/components/ArticleComponent';
import { NextSeo } from 'next-seo';

export default function Honduras(props) {

  const title = 'The fear of kidnapping does not stop the exodus from a tormented country';
  const description = 'To understand the exodus of the Honduran people, we must review the history of the last decade of this country: a coup d&apos;&eacute;tat, a looted and poor country, and a narco-state.';
  const featuredImage = 'https://migrantes.vozdeguanacaste.com/banner-honduras.jpg'
  const autor = "Written by: Allan Bu";
  const fotografia = "Photographs by: Jorge Cabrera";
  const medio = '<a target="_blank" href="https://twitter.com/ContraC_HN">@ContraC_HN</a>';

  const BodyComponent = (
      <div>
        <p className='excerpt'>To understand the exodus of the Honduran people, we must review the history of the last decade of this country: a coup d&apos;&eacute;tat, a looted and poor country, and a narco-state. In Lucerna, a small border town in western Honduras, a worker can earn 36 dollars a week, but in the United States he can earn up to 22 times more in that same time. This is a story that repeats itself in the town and in the entire country: being kidnapped, beaten, and abandoned in the desert to achieve the dream of leaving Honduras and living with dignity in a foreign country. There is no fear that is worth in the face of those calculations of survival.</p>
        <h2><strong>1. Lucerna</strong></h2>
        <p>Lucerna is a small town in Ocotepeque, located in western Honduras, which borders El Salvador and Guatemala. With dusty streets and modest housing, this town has experienced an unusual migration in the last four years. In addition, that migration already shows changes in the town: in contrast to the peasant houses, there are now large houses, with modern designs on the roofs, large windows and facades similar to the models built in American suburbs.</p>
        <p>Most of these houses built up with the money sent by the migrants, who left their town due to the lack of opportunities to live with dignity. In that town, a day laborer who works in agriculture earns just 150 lempiras a day (U$7). If they work all week, they would add 900 lempiras (US$36), but in the United States, they can earn 700 or 800 dollars in the same period. That is why they leave the country.</p>
        <p>In 2021 alone, at least 30 young people from the town of Lucerna undertook their journey to the United States, according to information from locals; seven of those migrants were kidnapped in northern Mexico. One of the kidnapped was Manuel, who in January 2021, decided to pack a suitcase and look for a new life in the northern country. His 17-year-old son accompanied him on the adventure. &ldquo;Sometimes it is because of the lack of work that we take those paths. It is complicated; we want to see if there is something there&rdquo;. He says.</p>
        <p>With the arrival of the pandemic and the destruction caused by storms Eta and Iota in Honduras, the country lost around half a million jobs, according to estimates by the Honduran Council of Private Enterprise (Consejo Hondure&ntilde;o de la Empresa Privada - Cohep). According to figures from the&nbsp;National Institute of Statistics&nbsp;(Instituto Nacional de Estad&iacute;sticas &ndash; INE) in 2020, the open unemployment rate reached 10.9%, the visible underemployment rate reached 27.3%, and the invisible employment reached 43%.</p>

        <figure>
            <img width="1500" height="1000" 
            src="https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937.jpg" alt="" 
            srcset="https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937.jpg 1500w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937-1024x683.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937-768x512.jpg 768w" sizes="(max-width: 1500px) 100vw, 1500px" />
            <figcaption>Un hombre camina por una siembra de papaya luego del paso de dos huracanes ETA y IOTA en Progreso; Honduras. Foto Archivo CC/Jorge Cabrera</figcaption>
        </figure>

        <p>The year 2020 was a fateful year for Micro, Small and Medium Enterprises (MSMEs). At least 10% had to close operations indefinitely due to the confinement decreed by the government to contain Covid-19. Before the Pandemic, Micro, Small and Medium Enterprises generated up to 70% of jobs in the country.</p>
        <p>For Honduras, the year 2020 represented a setback in its economy of 10.9%, according to estimates by the Central Bank of Honduras (Banco Central de Honduras (BCH). In 2019, the NIS established that the percentage of poverty in the country was 59%. In 2020, this government institution did not provide information in this regard. However, by 2021,&nbsp;the survey applied by the NIS showed that poverty reached 73.6%&nbsp;of Honduran households.</p>
        <p>Manuel left the country because of that poverty, and with effort, he paid 8 thousand dollars to a coyote, a human trafficker, who would cross him and his son across the border between the United States and Mexico. Manuel says that on the way, the coyote advised them to turn themselves in to the Border Patrol, to make an asylum request, but when passed, they had no chance of anything, and they were force to return, almost immediately to the border city of Reynosa, in the state from Tamaulipas.</p>
        <p>He wanted to cross back into the United States, when he was already in Mexico he received a call from the coyote, who told him that he was going to pick him up at the Reynosa Bridge, which crosses the Rio Grande, as he recalls. However, moments later, when he and his son left the place where they were sheltered, than they were kidnapped.</p>
        <p>&ldquo;The kidnappers have well-guarded, those border crossings, the taxi drivers and even the police are allied, says Manuel, who had to pay another four thousand dollars to obtain his freedom and that of his son&rdquo;.</p>
    
        <figure>
            <img width="2000" height="1335" src="https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972.jpg" alt="" srcset="https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972.jpg 2000w, https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972-1024x684.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972-768x513.jpg 768w, https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972-1536x1025.jpg 1536w" sizes="(max-width: 2000px) 100vw, 2000px" />
            <figcaption>Migrantes que buscaban llegar a Estados Unidos, en su mayor&iacute;a hondure&ntilde;os y nicarag&uuml;enses, en una caravana que pretend&iacute;a llegar a Estados Unidos el 15 de enero de 2022. San Pedro Sula, Honduras. Aproximadamente 500 migrantes de Honduras y Nicaragua se reunieron en San Pedro Sula, Honduras, para formar una caravana con destino a Estados Unidos. Los migrantes huyen de la inseguridad y la falta de oportunidades de empleo en sus pa&iacute;ses. Foto Archivo CC/Jorge Cabrera</figcaption>
        </figure>
        
        <p>Reynosa is the third city where the most kidnappings of migrants were registered, according to statistics from the non-profit organization Stop Kidnapping. Between December 2018 and July 2021, were reported 49 kidnappings, but this figure does not count migrants who did not report to authorities or who did not tell their story to a media outlet. In 2021,&nbsp;the Anti-Kidnapping Unit of the Tamaulipas Attorney General&apos;s Office&nbsp;reported that they had released 235 migrants, held against their will in the towns of Tamaulipas and Miguel Camargo.</p>
        <p>Manuel was kidnapped for three days. Those who deprived him of liberty called themselves &ldquo;The Trickers&rdquo; (Los Ma&ntilde;as), according to what he heard. The Honduran said that at that time there were more than 60 migrants in the warehouse where they were locked up. That figure of a single day exceeds the record of complaints that the Stop the Kidnapping organization has in almost three years.</p>
        <p>In order to pay the amount they asked for, he called his wife in Honduras, but she could not send the money that had to arrive in Mexico in parts, due to banking restrictions in the country. A friend who lives in the United States lent him four thousand dollars, the money that Manuel had to pay once he was back in Honduras.</p>
        <p>He remembers that those who kidnapped him were not such violent types, but they were well armed. They did not hit anyone, but they did not let us out either. They had us in a pasture and the migration officials came to rescue us when almost all of us had already paid, says Manuel.</p>
        <p>After the experience, he distrusts the coyote that took him to the border. &ldquo;It is that he called me that he was coming to pick me up to take me to a warehouse and we only walked a little and he gave us to other fucked up. In Mexico there is everything,&rdquo; says Manuel from his house in Lucerna, which he built with adobe, a material widely used in rural areas of western Honduras. After what happened in Mexico, Manuel returned to work in agriculture.</p>
        <p>&ldquo;I heard stories that the police detained people that the coyotes had hidden waiting to cross, but instead of deporting them they handed them over to criminals. It&apos;s just one mob. The pass in Mexico was perhaps easier before, but now it is difficult&rdquo;, says Manuel. Despite knowing this and fear, in September 2021, his son took the road to the United States again. This time, he achived to get there and already found a job. &quot;They almost kidnapped him again, he was saved because the coyote divided the group,&quot; he says.</p>
    
        <blockquote>
            <p>&ldquo;Escuch&eacute; historias que la polic&iacute;a(en M&eacute;xico) deten&iacute;a a gente que los coyotes ten&iacute;an escondidos para cruzar, pero en lugar de deportarlos se los entregaban a los delincuentes. Es una sola mafia&rdquo;. Manuel</p>
            <footer><a href="https://twitter.com/intent/tweet?text=%E2%80%9CEscuch%C3%A9+historias+que+la+polic%C3%ADa%28en+M%C3%A9xico%29+deten%C3%ADa+a+gente+que+los+coyotes+ten%C3%ADan+escondidos+para+cruzar%2C+pero+en+lugar+de+deportarlos+se+los+entregaban+a+los+delincuentes.+Es+una+sola+mafia%E2%80%9D.%0AManuel%0A&url=https%3A%2F%2Fcontracorriente.red%2F%2F2022%2F03%2F24%2Fel-temor-al-secuestro-no-detiene-el-exodo-de-un-pais-atormentado%2F&via=ContraC_HN" target="_blank">Tuit</a></footer>
        </blockquote>
        <h2><strong>2. From de banana field</strong></h2>
        <p>The children of Don Filiberto, a 57-year-old man, left northern Honduras on September 9, 2021, in path to the United States. Like thousands of their compatriots, they were seduced by the idea of a job with better income for family welfare, but the dream of the two boys only took one day to become a nightmare. On September 10, the two young were kidnapped in the Mexican state of Tabasco.</p>
        <p>That day, they were walking along a state highway, when Mexican police officers, who were driving in a patrol car, stopped and told them that if they did not get out of the way they would have to be arrested, according to their father&apos; story. The frightened young people followed the advice of the authority and when they took the path, it took them directly to the unidentified criminal group that kidnapped them.</p>
        <p>On September 11, after 24 hours kidnapped, the criminals called Don Filiberto to request a rescue, which was around 200,000 lempiras ($10,000). He remembers that call very well: &quot;I told them: I don&apos;t have money,&quot; he says. The kidnappers sent a video in which the two boys were brutally beaten. &ldquo;Now finish them off,&rdquo; the father told a man who called him to ask about the rescue. &quot;Is that what you want? Well, tomorrow we&apos;ll kill them,&quot; they replied.</p>
        <p>In the first six months of 2020, at least 3,250 migrants suffered attacks such as kidnapping, rape, armed robbery and human trafficking, while they await a response to their asylum requests on the northern border of Mexico with the United States; according to information collected by the international organization called Human Rights First (HRF).</p>
        <p>The organization The Other side (Al Otro Lado), which works with migrants in the city of Tijuana in Mexico, consulted for records of kidnappings on the border for this investigation. They responded via email that they did not have a specific number of Hondurans kidnapped, but from the 83% of 20,000 migrants of different nationalities surveyed, they reported having been victims of some form of violence.</p>
        <p>Migrants suffer different aggressions on their paths to the north, of all the most visible and know in media is kidnapping, which has become a business that generates billions of dollars, according to Rub&eacute;n Figueroa, an activist from the Mesoamerican Migrant Movement (MMM).</p>
        <p>According to Mr. Figueroa, the phenomenon cannot occur without the collaboration of the authorities. &quot;We are not only talking about bribery, but about direct participation in human trafficking,&quot; he says. This consideration coincides with the testimony of kidnapped migrants consulted for this investigation.</p>
        <p>In 2015, a report by the&nbsp;Foundation for Justice and the Democratic State&nbsp;(Fundaci&oacute;n para la Justicia y el Estado Democr&aacute;tico de Derecho &ndash; FJEDD), identified the nationality of 552 kidnapping victims: 372 Hondurans, 101 Salvadorans, 74 Guatemalans, and 5 Nicaraguans. There were another 609 victims of whom, only be verified that they were Central Americans. Among the kidnapped people, there were also Ecuadorians, Brazilians and Peruvians. That same report maintains that 55% of the migrants were kidnapped in southern of Mexico; 11% in the north; 1.2% in the center and 32% it was not possible to specify where they were arrested.</p>
        <p>The problem is not new and unknown either. In August 2010, the news of the murder of 72 Central American migrants in San Fernando, Tamaulipas, placed the kidnapping of undocumented immigrants on the front pages and, according to a report by United Nations High Commissioner for Refugees &ndash; UNHCR, this fact&nbsp;forced the government of Mexico, &quot;to recognize the magnitude of the problem of the kidnapping of migrants.&quot;</p>
        <p>The massacre was attributed to the Los Zetas Cartel, one of the bloodiest in the Aztec territory that was dedicated to drug trafficking, fuel theft and extortion, among other crimes. Today there are small cells throughout the country, kidnapping and extracting thousands of dollars from migrants, who are usually poor.</p>
        <p>Don Filiberto says that he watched helplessly how his children were brutally beaten in a video that went viral on the networks. After seeing the publication, he argued with the kidnappers and the last words he heard were &quot;Today we kill them.&quot;</p>
        <p>&quot;God freed them,&quot; says Don Filiberto. His children tell him that they were beaten for 10 hours and when they passed out, the kidnappers tried to disappear the bodies. &quot;They did not lose consciousness and heard the criminals say: we are going to bring some shovels to bury these dogs. They no longer sent the money,&quot; says the father. His children told him that they got up and fled after their kidnappers disappeared. After walking for three days, they managed to reach a house, where they received help, but that day a group of men arrived asking for two young immigrants.&nbsp;The lady who helped them said that she had not seen them and then sent the boys by taxi to the city of Palenque, still in Tabasco, where they were treated at a medical center and recovered for 15 days in a safe place.</p>
    
        <figure>
            <img width="2000" height="1335" src="https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935.jpg" alt="" srcset="https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935.jpg 2000w, https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935-1024x684.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935-768x513.jpg 768w, https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935-1536x1025.jpg 1536w" sizes="(max-width: 2000px) 100vw, 2000px" />
            <figcaption>Una migrante camina con su hija en los hombros hacia la frontera hondure&ntilde;a en medio de una caravana que pretende llegar a Estados Unidos el 15 de enero de 2022. San Pedro Sula, Honduras. Foto Archivo CC/Jorge Cabrera</figcaption>
        </figure>

        <p>Don Filiberto considers that his children were not kidnapped by any cartel, but by thieves from Mexico and Guatemala who have joined forces to commit crimes: &quot;The worst thing is that even if they send money, they always kill them. My children say that they once saw that they sent money and killed people,&quot; he says.</p>
        <p>The National Search Commission in Mexico, which has data since 1964, records that there are almost 100,000 missing persons in that country. Between September 2020 and the end of July 2021, the agency indicates that 6,453 cases were reported. Mexico is a country plagued by violence and has a war against drug trafficking; according to the Political Animal Media (Animal Politico), it leaves around 30,000 deaths a year.</p>
        <p>For Don Filiberto&apos;s children, the nightmare continued. They regained strength and returned to the United States and crossed the border, but they were arrested by US immigration, who had a request from the Mexican prosecutor to return the two Hondurans to that country. &quot;They were beaten again, the officers asked them what they had done so that they were looking for them,&quot; says Don Filiberto.</p>
        <p>When the case transcended on social networks, the Mexican prosecutor&apos;s office acted ex officio. For this reason, they were arrested at the border, then deported to Mexico, instead of Honduras. The two brothers received a humanitarian visa and began the process of requesting asylum in the United States.</p>
        <p>Javier Mart&iacute;nez, a worker at the Migrant House (Casa del Migrante) in Saltillo, Coahuila, affirms that the response of the Mexican authorities in crimes against migrants is very bad and according to his calculations, 99% of these cases go unpunished. &quot;In the work that we do, we have access to complaints and demands files of human rights violations, the problem is that it never lands, the complaints never reach the hands of a judge,&quot; he says.</p>
        <p>He believes that cases prosper only when the situation is in the media. &quot;It would have to be a very media case in which the authorities are being observed by the media or civil society, but otherwise things remain under investigation,&quot; says Mart&iacute;nez.</p>
        <p>Don Filiberto tells his story and that of his children, from his house located in one of the former banana fields in El Progreso, Yoro, in northern Honduras. The place that was once the headquarters of the &ldquo;banana republic&rdquo;, a term used to describe a poor, corrupt country with little democracy, low-value exports and performance at the pace of foreign interests.</p>
        <p>There, where their children grew up, the nostalgia of the banana plantation remained, although it is no longer the same, there are still many export banana plantations the new predominant monoculture that is African palm. There are also many stories of young people who left because there was no development thanks to those plantations.</p>
        <p><strong>3. Migration is news on television</strong></p>
        <p>The son of teacher Aminta was kidnapped by Los Zetas. That is what she says. This young man had to run away from Honduras, after receiving a threat from gang members in the neighborhood where he lived in San Pedro Sula, which is the main city in the north of the country. In the search to save his life, he nearly lost it. Alejandro, as we will call the teacher&apos;s son, was kidnapped twice, but before of these events he almost die in a container that transported almost 200 migrants.</p>
        <p>As it was a movie, the teacher was able to see through the signal of an American channel the moment when the police opened the container and some of the undocumented immigrants almost fainted, but her son jumped into a bush and run away from the authority. That escape was the beginning of the nightmare. &quot;That&apos;s when I knew he was alive,&quot; says the teacher.</p>
        <p>Advancing without the company of a coyote, Alejandro almost immediately fell into the hands of the Zetas. At the time that the teacher was at the school giving classes to her students, she received a call requesting approximately 4,000 dollars. &quot;You have to give me time,&quot; she said and, as she recalls, they answered her: &quot;You don&apos;t have time, move and be careful, talk to the police because we know all that.&quot;</p>
        <p>Rub&eacute;n Figueroa of the MMM, analyzes that currently criminal groups are currently kidnapping without discrimination: &ldquo;everyone is kidnapped, but much more the poorest&rdquo;, he says. Figueroa refers to the fact that before they did a kind of investigation of kidnapped people and, if they had relatives in the United States, they demanded money. &ldquo;Migrants who have no relatives in the United States were released after torture and mistreatment. Today criminals try to get water even from a stone,&quot; says Figueroa. The activist in favor of migrants, who points out that the most vulnerable people are the undocumented who have not paid a coyote.</p>
    
        <figure>
            <img width="2000" height="1335" src="https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737.jpg" alt="" srcset="https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737.jpg 2000w, https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737-1024x684.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737-768x513.jpg 768w, https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737-1536x1025.jpg 1536w" sizes="(max-width: 2000px) 100vw, 2000px" />
            <figcaption>Los migrantes hacen una cola para recibir comida y ropa, mientras esperan formar una caravana que pretende llegar a Estados Unidos el 15 de enero de 2022. San Pedro Sula, Honduras. Foto Archivo CC/Jorge Cabrera</figcaption>
        </figure>

        <p>Claudia Pinto, coordinator of the FJEDD office in Honduras, affirms that since the kidnappings of migrants began to be documented in 2009, it have not stopped happening; however, they are now much more visible. She adds that most of the people who are leaving the country do not have money to pay a trafficker, which makes them more vulnerable. &quot;It sounds ugly to say, but people who pay a coyote pay a certain amount of security, unlike people who don&apos;t and go alone,&quot; he says.</p>
        <p>In the last four years, Honduras has registered an unprecedented migratory flow, which had its maximum expression in the caravans organized in 2018. These brought together up to 15,000 Hondurans who walked together to the southern border of the United States. The last precedent was in January 2021,&nbsp;when some seven thousand Hondurans wanted to cross Guatemalan territory,&nbsp;but they were beaten by that country. However, that is the visible and extraordinary flow. The truth is that between 300 and 500 Hondurans leave the country&apos;s border points every day. They do it without registration and without leaving a trace.</p>
        <p>There is no exact number of the exodus, but&nbsp;according to the United States Customs and Border Protection Service, in 2020, they arrested 40,091 Hondurans, who were trying to enter the United States irregularly and until September 2021, this amount increased to 98,554 Honduran arrests, more than double the previous year.</p>
        <p>Aminta, the teacher, explains that she had to use all her savings in the bank to pay the rescue demanded by her son&apos;s kidnappers. She sent the money in five parts, because the bank did not allow him to send it in one transaction. After paying, the same criminal group arranged for Alejandro and other kidnapped migrants to reach the border. When they lent the young man the phone to communicate with her, he told her some details. On one occasion, he told her that the kidnappers put him and other migrants who remained captive, to dig a huge hole without knowing why. &ldquo;There is no question here, mom. Those of us who paid are calm, but we haven&apos;t seen those who didn&apos;t&rdquo;, recalls the teacher that her son told her.</p>
        <p>Once on the border between Mexico and the United States, Alejandro fell into the hands of another criminal group that called itself the &quot;Black Scorpions.&quot; It had only been a little over a month since the previous kidnapping. Now the rescue cost 5,000 thousand dollars.</p>
        <p>The teacher had to apply for several loans and was unable to obtain the requested amount immediately. She took about twelve days and during that time, her son was tortured. They made a video call to him, showing his son tied up and his captors grilling meat. The criminals tortured Alejandro by placing the hot grill on him.</p>
        <p>After paying the rescue, the teacher&apos;s son was found in US territory and members of the border patrol help him. &nbsp;He was seriously beaten, his kidneys were badly damaged from the beatings he received and he was transferred to Houston, where he was in a hospital for almost two months. When his health condition improved, he was deported. In Honduras, he needed a psychologist to recover from his mental health.&nbsp;&ldquo;On that road everything is money. The cartels think that migrants carry money and they don&apos;t care if they carry money or not. You have to look for it&rdquo;, says the teacher.</p>
        <blockquote>
            <p>&ldquo;En ese camino todo es dinero. Los carteles piensa que los migrantes llevan dinero y no les importa si llevan o no. Usted tiene que buscarlo&rdquo;. Madre de un migrante secuestrado</p>
            <footer><a href="https://twitter.com/intent/tweet?text=%E2%80%9CEn+ese+camino+todo+es+dinero.+Los+carteles+piensa+que+los+migrantes+llevan+dinero+y+no+les+importa+si+llevan+o+no.+Usted+tiene+que+buscarlo%E2%80%9D.%0AMadre+de+un+migrante+secuestrado&url=https%3A%2F%2Fcontracorriente.red%2F%2F2022%2F03%2F24%2Fel-temor-al-secuestro-no-detiene-el-exodo-de-un-pais-atormentado%2F&via=ContraC_HN" target="_blank">Tuit</a></footer>
        </blockquote>

        <p>The lack of hope prevails. After the terror experienced after going through two kidnappings and after many days crying over memories, Alejandro, the teacher&apos;s son, decided to set out again on the road to the United States. This time he succeeded and he is working.</p>
        <p>News of migrant kidnappings abound in the media. However, it seems that from the governments involved, this crime is unseen. Claudia Pinto, coordinator in Honduras of the Foundation for Justice, points out that she has heard Mexican President Manuel L&oacute;pez Obrador say, &quot;Nothing has happened in Mexico.&quot; He adds, &ldquo;This is very serious because he is evading its responsibility as a State; and the abandonment of our authorities in Honduras is also serious, because they do nothing to seek coordination between countries. They are states with structure and could coordinate search and rescue actions, but this does not happen&rdquo;.</p>
        <p>In Honduras, this crime is also unseen. For this investigation, a request was made through the Law of Access to Public Information, to the Chancellery of the Republic, in order to knowing the numbers of migrants who have reported kidnappings. However, they responded that these records were in the Security Secretariat, which coordinates with Interpol. Another request for information we made, which was also not resolved.</p>
        <p>In addition, we attempted to contact the vice chancellor of the previous government, Nelly Jerez, but she did not respond to the messages sent to her. Lastly, we request information on kidnappings of Hondurans to the Saltillo Consulate in Mexico. From this office, they limited themselves to saying that they were forbidden to give any information or interview.</p>
        <p>Will they stay to see a change in Honduras?</p>
        <p>The exodus does not stop. Organizations such as the Pastoral for Human Mobility estimate that between 300 and 500 Hondurans leave daily, they preferring to leave a country subjected to violence, organized crime, corruption and even climate change. Honduras has an average of 40 deaths per 100 thousand inhabitants associated with common violence, organized crime and drug trafficking. A high rate for a country that is not at war. Many neighborhoods in the main cities are still under the control of maras and gangs, although the previous government boasted of its security policy.</p>
        <p>However, drug trafficking has been linked to the last two presidents of Honduras. Tony Hern&aacute;ndez, brother of former President Juan Orlando Hern&aacute;ndez; and Fabio Lobo, son of former president Porfirio Lobo, who were convicted of drug trafficking by US justice. Former president Hern&aacute;ndez was accused of having links with drug trafficking in the trials against his brother and Giovanni Fuentes Ram&iacute;rez; now he is requested in extradition by the United States and he is arrested in the facilities of the Special Forces of the National Police. A sentencing judge has already granted the extradition, but the defense will appeal to the Supreme Court of Justice.</p>

        <figure>
            <img width="2560" height="1707" src="https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-scaled.jpg" alt="El ex presidente Juan Orlando Hernandez es presentado ante los medios luego de su captura en Tegucigalpa, Honduras." srcset="https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-scaled.jpg 2560w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-1024x683.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-768x512.jpg 768w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-1536x1024.jpg 1536w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-2048x1365.jpg 2048w" sizes="(max-width: 2560px) 100vw, 2560px" />
            <figcaption>El ex presidente Juan Orlando Hernandez es presentado ante los medios luego de su captura en Tegucigalpa, Honduras. Foto CC/Jorge Cabrera</figcaption>
        </figure>

        <p>The tragic scenarios do not end there. In June 2021, Ricardo Z&uacute;niga, the main official of the Joe Biden government for relations with Guatemala, El Salvador and Honduras, stated that corruption in Honduras drains approximately 3 billion dollars a year. He said this after the previous government executed a disputed purchase of seven mobile hospitals for 47 million dollars. According to the National Anticorruption Council, (Consejo Nacional de Anticorrupci&oacute;n - CNA) there was an overvaluation of 31 million dollars.</p>
        <p>In the Elections, November 2021, the National Party lost the elections after 12 years in government. Xiomara Castro, of the Liberty and Refoundation Party&nbsp;(Partido Libertad y Refundaci&oacute;n -&nbsp;LIBRE), became on January 27, 2022, the first woman to hold the presidency of Honduras. His victory was celebrated by crowds in the streets and filled with hope a large part of the population. In her first speech, after hearing the first vote count on November 28, Mrs. Castro said that her government would work so that no young person would have to migrate any more to survive. Despite the hopes that her speech raises in some people, the exodus continues.</p>
        <p>A few days after the inauguration of the Castro presidency, on January 15, 2022, a new caravan was organized at the Gran Terminal de San Pedro Sula. About 600 people walked to the Corinto border, between Guatemala and Honduras, the majority were Hondurans, but a large group of Nicaraguans also went. In that caravan was Javier, a Honduran who has been unemployed for four years and is the father of two daughters. &quot;We know that there was a change of government, but the country is sick and its recovery will be slow,&quot; he said.</p>
        <p>In Lucerna, the town where seven of the young people who migrated in 2021 were kidnapped, Fredy, a 42-year-old man, plans to travel to the United States. He will do it this year. He, like Don Filiberto&apos;s sons, Alejandro and Manuel, is willing to cross a path ravaged by death, in order to leave behind the hardships of a tormented country.</p>
  
      </div>
  )

  return (
      <div>
        <NextSeo
          title={title}
          description={description}
          canonical="https://migrantes.vozdeguanacaste.com/"
          openGraph={{
            title: title,
            description: description,
            images: [
              { url: featuredImage }
            ],
            site_name: title,
          }}
          twitter={{
            handle: '@handle',
            site: '@site',
            cardType: 'summary_large_image',
          }}
        />
        <main className="main-container">
          <ArticleComponent lang={'en'} title={title} featuredImage={featuredImage} body={BodyComponent} autor={autor} medio={medio} fotografia={fotografia} />
          <Header lang={'en'}/>
          <Footer/>
        </main>
      </div>
  );
}

