import Head from 'next/head';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { NextSeo } from 'next-seo';
import ArticleComponent from '@/components/ArticleComponent';

export default function Nicaragua(props) {

  const title = 'The United States is the new destination for Nicaraguans urgently fleeing Ortega&apos;s repression';
  const description = 'Driven by state violence and the lack of opportunities under the dictatorship of Daniel Ortega, thousands of Nicaraguans have decided to risk their lives and migrate north.';
  const featuredImage = 'https://migrantes.vozdeguanacaste.com/banner-nicaragua.jpg'
  const autor = "Text and photos: Divergentes";
  const fotografia = false;
  const medio = '<a target="_blank" href="https://twitter.com/DivergentesCA">@DivergentesCA</a>';

  const BodyComponent = (
    <div>
      <p className='excerpt'>Driven by state violence and the lack of opportunities under the dictatorship of Daniel Ortega, thousands of Nicaraguans have decided to risk their lives and migrate north. Historically, their destination had been Costa Rica, but the direction has changed. More and more Nicaraguans are joining the caravans of Central Americans who parade year after year with their dreams to leave a region that marginalizes them. The number of Nicaraguans detained at the U.S. southern border has reached unprecedented numbers. &quot;Nicaragua is going to empty out like Venezuela,&quot; these new migrants warn.</p>
      <p>Affliction, anguish, boldness, fear. That mix of all those feelings left their mark on Ramon Blandon when he crossed the border between Mexico and the United States in May of 2021. Although now that he thinks about it, he said, there was also a lot of stupidity. Not for having crossed, but for doing it with a group of friends without the guidance of a &ldquo;coyote,&rdquo; a human trafficker, on land where &ldquo;the owners are drug traffickers,&rdquo; said Blandon, a 37-year-old Nicaraguan. &ldquo;I don&apos;t know what would have happened to us if, by looking for the [American] dream, we had run into the &lsquo;owners&rsquo; of the road,&rdquo; he added.</p>
      <p>Blandon and his group planned a path to avoid the footprints that migrants leave with their steps. It wasn&rsquo;t easy at all. In fact, the only way he could explain how he and his friends survived it was by &quot;pure luck or God&apos;s blessing.&quot; To give an idea, he traveled the entire route with his body full of thorns, enduring low temperatures in arid mountains where he spent the night on dry branches, as shown in several photographs he has of the journey, in which he appears with a sorrowful face while trying to mitigate the cold with a shirt wrapped around his head like a hood. Of course, they were situations that he had imagined he would experience, but that didn&rsquo;t make it any less terrible when he experienced them in the flesh. &quot;You just get up the desire for the family,&quot; he added. &quot;It was the only thing I thought about.&quot;</p>
      <p>Ramon Blandon thought about his daughter that he left behind in Nicaragua, about his wife, and that he had to cross over to the United States &ldquo;to get ahead for them.&rdquo; But he also thought about how he couldn&rsquo;t go back to his country because he was being persecuted by military-style groups from the Sandinista Front and the National Police after he joined the protests in April of 2018, when the political crisis broke out.</p>
      <p>And not only that. Blandon had become unemployed. The pandemic ended up bankrupting the electric power company where he worked as a supervisor. So, in early 2021, when he learned that the borders had returned to normal, he set out for the United States. He did it alone, and when he arrived in Mexico, he thought about staying to work and asking for asylum. He stayed there for a few months, until his immigration application was denied. Feeling unprotected legally and hearing that the immigration policies of the new president of the United States, Joe Biden, &ldquo;had become more flexible&rdquo; with citizens of Cuba, Venezuela and Nicaragua, the countries with dictatorships, Blandon decided to cross the border in May of 2021. Before leaving, he called his wife and told her that he was going to attempt it and not to tell anyone else. &ldquo;If I can, I&apos;ll get in touch, and if I can&apos;t, I won&apos;t... You&apos;ll find out I&apos;ve arrived if you get a call,&rdquo; Blandon told his wife in a brief communication.</p>
      <figure>
          <img width="2048" height="1536" src="https://www.divergentes.com/wp-content/uploads/2022/03/Ramo%CC%81n-Bland.jpg" alt="" srcset="https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland.jpg 2048w, https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland-300x225.jpg 300w, https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland-1024x768.jpg 1024w, https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland-768x576.jpg 768w, https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland-1536x1152.jpg 1536w, https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland-500x375.jpg 500w, https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland-800x600.jpg 800w, https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland-1280x960.jpg 1280w, https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland-1920x1440.jpg 1920w, https://www.divergentes.com/wp-content/uploads/2022/03/Ramón-Bland-337x253.jpg 337w" sizes="(max-width: 2048px) 100vw, 2048px" />
          <figcaption>En los &uacute;ltimos meses Ram&oacute;n Bland&oacute;n ha trabajado de forma espor&aacute;dica como alba&ntilde;il e ingeniero. Foto: Cortes&iacute;a.</figcaption>
      </figure>
      <p>The United States, Blandon&rsquo;s destination, is the one that&rsquo;s having the greatest surge among Nicaraguans. Between January and November 2021, the United States Border Patrol recorded that 71,667 Nicaraguans tried to enter along the southern border without documents.</p>
      <p>According to Manuel Orozco, director of the immigration, remittance and development program at the Inter-American Dialogue center for political analysis and exchange, this phenomenon can only be compared to the crisis of the 1980s caused by Ortega&apos;s abuse of power during the first Sandinista term. At that time, more than 120,000 people left for the United States, tripling the immigrant population.</p>
      <p>In July of 2021, 13,391 Nicaraguans were registered at the border, almost double the number registered in June (7,441) and more than triple the number in May (4,451). In 2017, a year before the political crisis of 2018, barely 1,000 Nicaraguans were apprehended, according to the United States Customs and Border Protection Office (CBP). The increase coincides with the crisis that Nicaragua has been experiencing since April of 2018, which worsened in 2021 with the arrests of&nbsp;<a href="https://www.divergentes.com/presos-por-retar-a-la-dictadura-ortega-murillo-en-las-urnas/">opposition leaders in the context of the election</a>.</p>
      <p>Inter-American Dialogue estimates that some 95,000 Nicaraguans fled the country in 2021 due to shutting down public liberties, unemployment and citizen insecurity. Of these, according to those calculations, 60,000 migrated to the United States and 35,000 to Costa Rica, the country that was the main migration destination for Nicaraguans for years.</p>
      <p>&ldquo;An unprecedented figure that reveals the seriousness of the situation in Nicaragua,&rdquo; said Wendy Flores, defender and lawyer for the human rights organization Nicaragua Nunca M&aacute;s (Nicaragua Never Again). &ldquo;The change in destination of the migratory flow is now heading north, a route marked by violence and insecurity,&rdquo; added Flores.</p>
      <p>Blandon explained that he chose the United States because of &ldquo;the bad economic situation I had,&rdquo; which didn&rsquo;t allow him to make a longer and more expensive trip to Spain. He had no relatives to support him in Costa Rica or in Panama. &ldquo;I just knew that I couldn&apos;t continue in the country,&rdquo; said Blandon, referring to Nicaragua.</p>
      <div className='iframe-container'>
        <iframe sandbox="allow-scripts" src="https://flo.uri.sh/visualisation/9000203/embed#?secret=E6ULUzlcjl" frameborder="0" scrolling="no" height="575" width="700"></iframe>
      </div>
      <h2><strong>Historical Migration to Costa Rica</strong></h2>
      <p>Nicaraguans began going into exile about 45 years ago, starting with the first clashes between the Anastasio Somoza Debayle dictatorship and the Sandinista Front guerrillas. However, the destination historically has been Costa Rica, according to an article in the magazine&nbsp;Env&iacute;o, written by Alberto Cortes Ramos, associate professor at the University of Costa Rica in the School of Political Science. Since before the overthrow of the Somocista dynasty, in the 1970s, it is estimated that 280,000 people left Nicaragua, and at least 80,000 went to Costa Rica. Years later, during the revolutionary project that became a dictatorship in the 1980s and that led to an armed confrontation between the Sandinista Army and the Counterrevolution, some 123,000 Nicaraguans&mdash;documented and undocumented&mdash; took refuge in Costa Rica.</p>
      <p>That&rsquo;s why the recent increase in migration to the United States is attracting media attention. More and more Nicaraguans are being seen among the Central American caravans. In July of last year, a month after the way out of the sociopolitical crisis was closed with the end of the elections by the regime of Daniel Ortega and Rosario Murillo, Nicaragua surpassed El Salvador as the Central American country with the third highest record of undocumented immigrants, after Honduras and Guatemala. The current exodus of Nicaraguans is even greater than the one caused by&nbsp;<a href="https://www.divergentes.com/justicia-y-memoria-en-nicaragua/">the brutal repression of the massive movements against the government in 2018</a>, which caused more than 300 deaths, hundreds of political prisoners, as well as people tortured and missing.</p>
      <p>According to data from the Transactional Records Access Clearinghouse of Syracuse University, during the 2020 fiscal year, 36% of asylum applications from Nicaraguan citizens were approved, a figure that is above the average for other nationalities. As of October of 2021, more than 34,000 Nicaraguans were waiting to have their cases heard by judges.</p>
      <figure>
          <img width="900" height="600" src="https://www.divergentes.com/wp-content/uploads/2022/03/8013972127001w.jpg" alt="" srcset="https://www.divergentes.com/wp-content/uploads/2022/03/8013972127001w.jpg 900w, https://www.divergentes.com/wp-content/uploads/2022/03/8013972127001w-300x200.jpg 300w, https://www.divergentes.com/wp-content/uploads/2022/03/8013972127001w-768x512.jpg 768w, https://www.divergentes.com/wp-content/uploads/2022/03/8013972127001w-500x333.jpg 500w, https://www.divergentes.com/wp-content/uploads/2022/03/8013972127001w-800x533.jpg 800w, https://www.divergentes.com/wp-content/uploads/2022/03/8013972127001w-380x253.jpg 380w" sizes="(max-width: 900px) 100vw, 900px" />
          <figcaption>Migrantes centroamericanos, entre ellos nicas, atraviesan M&eacute;xico para llegar a Estados Unidos. EFE.</figcaption>
      </figure>
      <p>During his election campaign, the president of the United States, Joe Biden, promised an in-depth review of the immigration policies of former President Donald Trump, which limited the right to asylum, cut off financing to foreign countries and toughened the requirements to obtain residency and citizenship, which caused immigration arrivals to the country to slow down a bit.</p>
      <p>In his first days in office, Biden suspended the construction of the border wall with Mexico, ordered the creation of a work group to reunite minors who were separated from their parents after crossing the border, and gave instructions to review the Migrant Protection Protocols (MPP) program, also known as &ldquo;Stay in Mexico,&rdquo; under which more than 60,000 asylum seekers were returned to that country to wait for the resolution of their case. However, an analysis done in August of 2021 by the Latin American Strategic Center for Geopolitics (CELAG for the Spanish acronym) noted that Biden&apos;s changes &ldquo;are few and express more continuities than break aways.&rdquo; According to the study, Biden &quot;is not attacking immigration deeply and at the root.&quot;</p>
      <p>Unlike Central American immigrants from the Northern Triangle (Guatemala, Honduras and El Salvador) who mainly flee due to gang violence, in Nicaragua they&rsquo;re escaping state violence. However, the United States began deporting a record number of Nicaraguans last year,&nbsp;<a href="https://www.reuters.com/world/americas/us-heads-record-nicaragua-deportations-despite-ortega-criticism-2021-11-25/">according to data reviewed by Reuters news agency</a>.</p>
      <p>In mid-November,&nbsp;Just The News&nbsp;reported that Nicaraguans who enter the United States with an illegal immigration status wouldn&rsquo;t be deported. However, a few days later, a spokeswoman for the U.S. embassy in Nicaragua stated that the Biden administration &ldquo;has made it clear that our borders are not open and that individuals and families are subject to border restrictions, including expulsion and deportation.&quot; The United States embassy in Nicaragua has been carrying out a campaign against illegal immigration to that North American country for several months, asking people not to make &ldquo;A Trip in Vain.&rdquo;</p>
      <h2><strong>An Ordeal that Took a Month and a Half</strong></h2>
      <figure>
          <img width="1599" height="899" src="https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando.jpg" alt="" srcset="https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando.jpg 1599w, https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando-300x169.jpg 300w, https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando-1024x576.jpg 1024w, https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando-768x432.jpg 768w, https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando-1536x864.jpg 1536w, https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando-500x281.jpg 500w, https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando-800x450.jpg 800w, https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando-1280x720.jpg 1280w, https://www.divergentes.com/wp-content/uploads/2022/03/Jacksell-trabajando-380x214.jpg 380w" sizes="(max-width: 1599px) 100vw, 1599px" />
          <figcaption>Despu&eacute;s de su trabajo, Jacksell Herrera se dedica a actualizar la p&aacute;gina web que cre&oacute; para compartir noticias pol&iacute;ticas de Nicaragua. Cortes&iacute;a.</figcaption>
      </figure>
      <p>Jacksell Herrera, 22, fled from Nicaragua because he was triple persecuted. First, because he worked in the Communications department of the mayor&apos;s office in Pantasma, one of the few municipalities opposed to the regime. Second, because he was a human rights defender for the Permanent Commission of Human Rights (CPDH for the Spanish acronym). And third, because he created a web page<a href="http://www.nicaraguanewsnn.com">&nbsp;to publish political news</a>, which is persecuted by the Ortega and Murillo regime.</p>
      <p>In December of 2020, Herrera was searched in Managua after he left an interview with&nbsp;<a href="https://www.divergentes.com/medardo-mairena-el-primer-lider-campesino-que-se-postulo-como-presidente/">Medardo Mairena, one of the presidential candidates who was imprisoned</a>. A month later, the police arrested him and forcefully put him in shackles when he was filming a police attack against opposers. That day, Pantasma&apos;s lieutenant, Denis Jarquin, told him, &quot;I&apos;m going to wipe that smile off your face.&quot; Herrera felt that it was a death threat. That,&nbsp;<a href="https://www.laprensani.com/2020/08/30/suplemento/la-prensa-domingo/2714802-quienes-son-los-periodistas-judicializados-conozca-sus-historias">in addition to the fact that the Prosecutor&apos;s Office opened a judicial proceeding against him</a> and Sandinista military-style groups and police threatened him with assassination every day on Messenger. In addition, one of his sources told him: &ldquo;They already have your file ready to throw you in jail.&rdquo; All of this caused him to flee the country on August 2, 2021.</p>
      <p>Herrera resigned from his job at the mayor&apos;s office two weeks before the trip. He got together the $5,000 to pay the coyote who took him to the border with the United States. One of these &ldquo;guides&rdquo; for the route to North America&nbsp;<a href="https://www.infobae.com/america/america-latina/2021/11/17/exodo-masivo-de-nicaraguenses-hacia-estados-unidos-se-dispara-por-la-crisis-politica-y-economica/">told Infobae that they charge $5000</a> to the border between Mexico and the United States, and $12,000 to be taken to the city of Houston, Texas. To get the full amount of money together, Herrera had to sell some belongings, collect his severance pay and take out a loan.</p>
      <p>It took 21 days from the time he left his house in Pantasma until he turned himself in at the U.S. border. Herrera said that 95 percent of the days were full of suffering: hunger, thirst, sleeplessness. Sleeping in moving vehicles, sometimes packed together with people who had to arrange themselves lying on top of each other. On one of those trips, he saw a seven-month-old baby in agony in his mother&apos;s arms from dehydration. &ldquo;They abandoned the trip because they had to go to the hospital in an emergency,&rdquo; he said. Most of the time, the migrant group was transferred to closed warehouses, where they endured heat or cold and tried to sleep on the floor.</p>
      <p>Despite all the suffering, Herrera said he was lucky. And he&rsquo;s not far from being right. At the beginning of November 2021, people learned of the<a href="https://www.laprensa.com.ni/2021/11/12/nacionales/2909655-cartel-mexicano-libera-a-siete-nicaraguenses-que-mantuvo-de-rehenes">&nbsp;stories of Gerleni Jimenez and Maria Teresa Delgadillo</a>, both from Matagalpa, who were kidnapped en route to the United States by a Mexican cartel that asked for $10,000 to free them. The families collected money and finally the girls were released on November 12.&nbsp;DIVERGENTES&nbsp;contacted their relatives, but they didn&rsquo;t want to talk about how the girls were released.</p>
      <figure className='two'>
          <figure><img width="225" height="300" src="https://www.divergentes.com/wp-content/uploads/2022/03/Foto-Ramon-2-225x300.jpeg" alt="" srcset="https://www.divergentes.com/wp-content/uploads/2022/03/Foto-Ramon-2-225x300.jpeg 225w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-Ramon-2-768x1024.jpeg 768w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-Ramon-2-500x667.jpeg 500w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-Ramon-2-800x1067.jpeg 800w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-Ramon-2-190x253.jpeg 190w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-Ramon-2.jpeg 960w" sizes="(max-width: 225px) 100vw, 225px" /></figure>
          <figure><img width="225" height="300" src="https://www.divergentes.com/wp-content/uploads/2022/03/Foto-brazalete-225x300.jpeg" alt="" srcset="https://www.divergentes.com/wp-content/uploads/2022/03/Foto-brazalete-225x300.jpeg 225w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-brazalete-768x1024.jpeg 768w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-brazalete-1152x1536.jpeg 1152w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-brazalete-500x667.jpeg 500w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-brazalete-800x1067.jpeg 800w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-brazalete-190x253.jpeg 190w, https://www.divergentes.com/wp-content/uploads/2022/03/Foto-brazalete.jpeg 1200w" sizes="(max-width: 225px) 100vw, 225px" /></figure>
          <figcaption>Antes de cruzar el r&iacute;o Bravo, los coyotes les colocaron este brazalete a Jacksell Herrera y otros migrantes para identificarlos como los que se iban a entregar a la Patrulla Fronteriza. Los que no ten&iacute;an brazaletes iban de &laquo;rodeo&raquo;, es decir, evitando a las autoridades de la frontera.</figcaption>
      </figure>
      <p>On January 15, the first caravan of migrants headed mainly by Nicaraguans left Honduras, according to&nbsp;<a href="https://contracorriente.red/2022/01/15/nicaragua-se-va-a-vaciar-como-venezuela-advierten-migrantes-que-van-en-caravana-huyendo-de-centroamerica/">Contracorriente, a news outlet</a>. &ldquo;Most of this group are Nicaraguan citizens who fled from the Daniel Ortega regime,&rdquo; that news outlet reported. &ldquo;Nicaragua is going to be empty out like Venezuela,&rdquo; said one of the Nicaraguans who fled in that caravan. According to information in the media and from the governments of Honduras and Guatemala, the caravan was made up of more than 1,000 people and was detained the next day by troops from Guatemala&rsquo;s army and national police force. The Associated Press reported that the agents and soldiers &quot;sprayed tear gas and used their clubs and shields&quot; on the group of migrants who tried to break through a fence along the highway that connects both countries, Honduras and Guatemala, in the Vado Hondo sector.&nbsp;</p>
      <p>Several groups of Nicaraguans were in the caravan, composed of up to 16 people, mostly relatives, who said they fled Nicaragua due to the crisis unleashed by the Ortega regime and state violence. This would have been the first large group of foreigners that was going to challenge Joe Biden&apos;s Migrant Protection Protocols, eliminated in February of last year but restored in December of 2021.</p>
      <p>The region is experiencing a record flow to the United States, whose Customs and Border Protection Office detected more than 1.7 million undocumented immigrants at the border with Mexico by the end of September 2021. Mexico intercepted more than 252,000 undocumented immigrants between January and November of last year and deported more than 100,000 in the same period, according to the Migration Policy Unit of the country&apos;s Secretary of State.</p>
      <h2><strong>&ldquo;Here I have freedom and security&rdquo;</strong></h2>
      <figure>
        <img src="https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-scaled.jpg" alt="" srcset="https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-scaled.jpg 2560w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-300x211.jpg 300w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-1024x721.jpg 1024w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-768x541.jpg 768w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-1536x1082.jpg 1536w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-2048x1443.jpg 2048w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-500x352.jpg 500w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-800x564.jpg 800w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-1280x902.jpg 1280w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-1920x1352.jpg 1920w, https://www.divergentes.com/wp-content/uploads/2021/11/8010624268001-359x253.jpg 359w" sizes="(max-width: 2560px) 100vw, 2560px" />
        <figcaption>La crisis sociopol&iacute;tica iniciada en abril de 2018 ha empeorada m&aacute;s, y la migraci&oacute;n de los m&aacute;s j&oacute;venes ha sido una de sus principales causas. EFE | Arrchivo.</figcaption>
      </figure>
      <p>Once he turned himself in to the border guard, Jacksell Herrera, the former municipal employee, was sent to different migrant detention centers in Texas. He was confined there for almost a month until he won his case in Immigration and was released on September 17, 2021. Since he had only notified five people about his trip, he wasn&rsquo;t able to say goodbye to his entire family, including his paternal grandfather, who died while he was on his way to the United States. &ldquo;It was very painful to find out about his death without being able to say goodbye,&rdquo; he said.</p>
      <p>Herrera now lives in Indiana, where he works repairing basements. &ldquo;I decided to come to the United States because I have better opportunities here&hellip; Here I do have freedom and security,&rdquo; he said. He still writes news for his web page and collaborates with the&nbsp;Nicaragua Actual&nbsp;platform. &quot;I dream of having my own media outlet,&quot; he added.</p>
      <p>Hundreds of miles away, in California, Ramon Blandon lives with his aunt and uncle, but not for long, because he hopes to move to another place. &ldquo;You know: the flower smells [nice] from a distance, but up close, it stinks,&quot; he said. He makes a living doing a little of everything: construction, loading and unloading trucks or landscaping. &ldquo;It&apos;s hard to be here, but someone has to make the sacrifice for the family to be well and in this case, it&rsquo;s me,&rdquo; he added. He&rsquo;s not sorry that he went to the United States because &ldquo;there&rsquo;s nothing more valuable than life&rdquo; and his was &ldquo;at risk&rdquo; in Nicaragua.</p>
    </div>
  )

  return (
      <div>
        <NextSeo
          title={title}
          description={description}
          canonical="https://migrantes.vozdeguanacaste.com/"
          openGraph={{
            title: title,
            description: description,
            images: [
              { url: featuredImage }
            ],
            site_name: title,
          }}
          twitter={{
            handle: '@handle',
            site: '@site',
            cardType: 'summary_large_image',
          }}
        />
        <main className="main-container">
          <ArticleComponent lang={'en'} title={title} featuredImage={featuredImage} body={BodyComponent} autor={autor} medio={medio} fotografia={fotografia} />
          <Header lang={'en'}/>
          <Footer/>
        </main>
      </div>
  );
}

