import Head from 'next/head';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ArticleComponent from '@/components/ArticleComponent';

export default function CostaRica(props) {

  const title = 'Xenofobia, la segunda pandemia que se propagó en Costa Rica';
  const description = 'Un estudio de Naciones Unidas reveló que en 13 meses de pandemia se registraron más de 180 mil comentarios xenofóbicos en Costa Rica.';
  const featuredImage = 'https://migrantes.vozdeguanacaste.com/banner-costarica.jpg'
  const autor = "Texto: Vladimir Vásquez";
  const medio = '<a target="_blank" href="https://twitter.com/VozdeGuanacaste">@VozdeGuanacaste</a>';
  const fotografia = "Fotografía: César Arroyo";

  const BodyComponent = (
      <div>
        <p className='excerpt'>Un estudio de Naciones Unidas reveló que en 13 meses de pandemia se registraron más de 180,000 comentarios xenofóbicos en Costa Rica, la mayoría de ellos contra los nicaragüenses. Los nicas se enfrentan al dilema de vivir con la discriminación o de regresar a Nicaragua a enfrentar la cárcel o la muerte.</p>
        <p>&ldquo;Mi problema es con este maldito nicarag&uuml;ense&rdquo;, le dijo un hombre alto, blanco y recio a Alberto, un joven nicarag&uuml;ense de 28 a&ntilde;os, antes de empezar a lanzarle patadas en las afueras de un bar en Guadalupe, una de las principales ciudades de San Jos&eacute;. El ataque no fue repentino. El agresor hab&iacute;a pasado cerca del bar en esa localidad y hab&iacute;a fijado su mirada sobre el nicarag&uuml;ense que se encontraba acompa&ntilde;ado de una salvadore&ntilde;a.&nbsp;</p>
        <p>Inicialmente no mostr&oacute; ning&uacute;n tipo de hostilidad. Se sent&oacute; en la mesa con ellos y hasta les ofreci&oacute; invitarles una cerveza para que platicaran. Las &ldquo;alertas&rdquo; se encendieron para Alberto cuando aquel hombre empez&oacute; a mostrarles sus tatuajes: una esv&aacute;stica, un sol negro y muchos s&iacute;mbolos m&aacute;s. Tambi&eacute;n alarde&oacute; de su entrenamiento: les dijo que practicaba artes marciales, que pod&iacute;a manejar armas de diferentes calibres, y les pregunt&oacute; con insistencia su nacionalidad, seg&uacute;n relata Alberto.&nbsp;</p>
        <p>&nbsp;&ldquo;Cuando pas&oacute; la primera vez por el bar me hizo un saludo nazi. Yo ya hab&iacute;a le&iacute;do sobre estas personas que se identifican como neonazis. Le dije a mi amiga que nos fu&eacute;ramos, ella sali&oacute; primero y con ella no tuvo ning&uacute;n tipo de agresi&oacute;n. Cuando me la estaba llevando, le dijo: &lsquo;el problema no es con vos, es con este maldito nicarag&uuml;ense&rsquo; y me tir&oacute; una patada&rdquo;, cuenta Alberto, quien ha preferido que no se revele su verdadero nombre para este reportaje por razones de seguridad.&nbsp;</p>
        <p>Alberto es un hombre moreno, delgado, originario de Le&oacute;n, en el occidente de Nicaragua. Lleg&oacute; a Costa Rica en 2020 para protegerse de la persecuci&oacute;n del r&eacute;gimen de Daniel Ortega contra quienes participaron en las protestas de abril de 2018. Seg&uacute;n los datos m&aacute;s recientes del Grupo de Expertos Interdisciplinarios (GIEI) de la Organizaci&oacute;n de Estados Americanos (OEA), esas protestas terminaron en m&aacute;s de 355 personas asesinadas por la represi&oacute;n gubernamental.&nbsp;</p>
        <p>Hasta ese 28 de febrero de 2020, d&iacute;a en que ocurri&oacute; la agresi&oacute;n, Alberto se sent&iacute;a seguro en Costa Rica. Cre&iacute;a que la persecuci&oacute;n hab&iacute;a quedado atr&aacute;s, pero su agresor vio su piel y su acento como suficientes elementos para atacarlo. Su amiga salvadore&ntilde;a decidi&oacute; defenderlo ante la lluvia de golpes y patadas lanzadas por aquel hombre. Recogi&oacute; una bolsa de basura en el suelo y se la lanz&oacute;. La pareja logr&oacute; salir del lugar y se refugiaron en la casa de otro amigo por si el agresor los persegu&iacute;a, seg&uacute;n el relato de Alberto.&nbsp;</p>
        <p>Cerca de los d&iacute;as en que se dio el ataque a Alberto, los casos de covid-19 estaban empezando a subir en Costa Rica. Para marzo de 2020 aumentaron las acusaciones y el acoso en redes sociales contra nicarag&uuml;enses migrantes. Los mensajes de odio para los extranjeros inclu&iacute;an acusaciones de propagar la enfermedad en el pa&iacute;s.</p>
        <p>&ldquo;Me dec&iacute;an que ven&iacute;amos a inundar el pa&iacute;s de covid&rdquo;, recuerda Juliana, una nicarag&uuml;ense que ha vivido casi 30 a&ntilde;os en Costa Rica, y a quien a diario le tocaba leer comentarios contra los nicarag&uuml;enses en Facebook.&nbsp;</p>
        <figure>
            <img src="https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-46.jpg" alt="" width="1920" height="1280" srcset="https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-46.jpg 1920w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-46-300x200.jpg 300w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-46-1024x683.jpg 1024w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-46-768x512.jpg 768w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-46-1536x1024.jpg 1536w" sizes="(max-width: 1920px) 100vw, 1920px" />
            <figcaption>La polic&iacute;a costarricense patrulla el sector de la frontera de Pe&ntilde;as Blancas conocido como El Muro. Diciembre de 2021, La Cruz, Guanacaste. Foto: C&eacute;sar Arroyo Castro</figcaption>
        </figure>
        <h2><strong>Medio mill&oacute;n de expresiones de odio&nbsp;</strong></h2>
        <p><a href="https://costarica.un.org/es/134834-investigacion-de-onu-identifica-mas-de-medio-millon-de-conversaciones-ligadas-discursos-de" rel="noopener" target="_blank">La Organizaci&oacute;n de Naciones Unidas (ONU), junto a la firma internacional COES</a>, determin&oacute; que desde el primero de mayo de 2020, tan solo dos meses despu&eacute;s de detectado el primer caso positivo de covid-19 en Costa Rica, hasta el 15 de junio de 2021, en las redes sociales se publicaron 548,020 conversaciones que inclu&iacute;an lenguaje discriminatorio en contra de diferentes grupos, entre ellos nicarag&uuml;enses.</p>
        <p>De todas esas conversaciones, 181 mil 453 eran expresiones xenof&oacute;bicas, es decir, el 33% de todos los resultados encontrados en el estudio inclu&iacute;an mensajes de odio para los extranjeros. La poblaci&oacute;n nicarag&uuml;ense fue la m&aacute;s afectada.&nbsp;</p>
        <blockquote>
            <p>Yo les dec&iacute;a que el covid ya estaba, que no era porque los nicas que ven&iacute;an ac&aacute; tra&iacute;an el virus. A m&aacute;s de uno le dije que eran xenof&oacute;bicos, pero me respond&iacute;an que ven&iacute;amos a quitarles el trabajo a los costarricenses&rdquo;, relata Juliana.</p>
        </blockquote>
        <p>En junio de 2020 se registr&oacute; el pico m&aacute;s grande de los comentarios en contra de nicas relacionados a falta de medidas de seguridad contra la covid-19 en cuarter&iacute;as (complejos de cuartos muy peque&ntilde;os donde viven familias de escasos recursos econ&oacute;micos).</p>
        <p>La cifra del estudio es grande si se compara con la cantidad de nicarag&uuml;enses que se encuentran en Costa Rica. El &uacute;nico censo oficial que se ha realizado para medir la cantidad de nicas que hay en el pa&iacute;s data de 2011, cuando se calculaba que hab&iacute;a 287,766 personas de esa nacionalidad. En la actualidad, los datos m&aacute;s conservadores de expertos en temas migratorios, calculan que hay m&aacute;s de medio mill&oacute;n de nicas en Costa Rica.&nbsp;</p>
        <p>Otro n&uacute;mero que permite entender el peso que tiene la poblaci&oacute;n nicarag&uuml;ense en Costa Rica es el del <a href="https://www.inec.cr/sites/default/files/documetos-biblioteca-virtual/renaho2020.pdf" rel="noopener" target="_blank">Instituto Nacional de Estad&iacute;sticas y Censos, que con datos de la Encuesta de Hogares (Enaho)</a> de 2020, calcul&oacute; que el 80% de la poblaci&oacute;n extranjera que vive en el pa&iacute;s naci&oacute; en Nicaragua. La migraci&oacute;n aument&oacute; en 2018, cuando el r&eacute;gimen de Daniel Ortega desat&oacute; una cacer&iacute;a de opositores que ped&iacute;an su renuncia al poder que hab&iacute;a ocupado, hasta ese momento, durante 11 a&ntilde;os. Los datos oficiales de Migraci&oacute;n y Extranjer&iacute;a costarricense indican que en, el 2021, 47,534 nicarag&uuml;enses pidieron refugio en Costa Rica, pero dentro de ese n&uacute;mero no se cuentan quienes llegaron en situaci&oacute;n irregular al pa&iacute;s. &nbsp;</p>
        <p>El 69% de las expresiones xenof&oacute;bicas ten&iacute;an la intencionalidad de ofender, se detalla en el estudio de la ONU, mientras que el 31% se bas&oacute; en la emisi&oacute;n de prejuicios y estereotipos, &ldquo;que si bien no ten&iacute;an necesariamente dicha intenci&oacute;n (de ofender), s&iacute; generaban discriminaci&oacute;n hacia ciertas poblaciones&rdquo;.</p>
        <p>Seg&uacute;n el mismo estudio, los hombres fueron los que m&aacute;s comentarios discriminatorios emitieron durante el per&iacute;odo estudiado con un 66% frente a un 48% de mujeres. Y las personas de 45 a&ntilde;os o m&aacute;s fueron las que mostraron la intencionalidad m&aacute;s alta de ofender con sus comentarios, con un 79%. Sumado a eso, la provincia que m&aacute;s comentarios de odio registr&oacute; fue la de San Jos&eacute;.&nbsp;</p>
        <p>Las publicaciones que se hac&iacute;an desde las cuentas oficiales de las instituciones de Costa Rica estaban llenas de reacciones con comentarios contra los nicarag&uuml;enses. Bastaba ver redes sociales de la Direcci&oacute;n de Migraci&oacute;n y Extranjer&iacute;a de Costa Rica, de la Caja Costarricense de Seguro Social (CCSS), y hasta de los medios de comunicaci&oacute;n.&nbsp;</p>
        <blockquote>
            <p><a href="https://www.facebook.com/ccssdecostarica/posts/3263845916972442?comment_id=3263879646969069&__cft__%5B0%5D=AZXRMaBCIUBPxGjVeLGcTb6Gy70OjGj6hsYu9QU_auqhhrCmCbLWmPGqe9CD2pXZ2CCIfkAt7JrXkaMptKyoU6vxJ7doF-KD4uTDj_PAyz9DpxFCpu-iwu9KwpbmTAi98KAJiULuKeaRV9Dg67GwleoDJETpGwdQedUhVpX0yEX71JUWNVN_losRjLarkgMTzRY&__tn__=R%5D-R" rel="noopener" target="_blank">Si los nuevos casos son los nicas, que est&aacute;n viniendo a contagiar a los ticos</a>&rdquo;, escrib&iacute;a en mayo de 2020 un hombre en las publicaciones de la CCSS sobre los casos de covid-19.&nbsp;</p>
        </blockquote>
        <p>&ldquo;Diay, si hay que exterminarlos, solo as&iacute; aprenden los hijueputas&rdquo;, amenazaba otro perfil en Facebook. &ldquo;Aporto 10,000 colones (U$15) para un fondo y crear el escuadr&oacute;n de linchamiento&rdquo;, dec&iacute;a uno m&aacute;s de los miles de comentarios que se pueden encontrar en diferentes publicaciones en las redes sociales.&nbsp;</p>
        <p>Las publicaciones discriminatorias se extendieron a lo largo y ancho de todo lo que mencionara nicarag&uuml;enses en las redes sociales. En Guanacaste, las publicaciones referentes a los refugiados nicarag&uuml;enses tambi&eacute;n se llenaron de comentarios xenof&oacute;bicos.&nbsp;</p>
        <p>Perfiles que fueron se&ntilde;alados por otros usuarios de redes de ser troles (expresi&oacute;n que se usa para identificar a personas que usan cuentas falsas para atacar, ofender o desviar la atenci&oacute;n de temas importantes) quer&iacute;an provocar caos.&nbsp;</p>
        <p><a href="https://www.facebook.com/vozdeguanacaste/posts/1883858611697458?comment_id=1884069498343036&__cft__%5B0%5D=AZUmOr7LK9IWsMKzRqyeMRBA3QJima4jO0tfaHybqw695AZg7fQ6fqJek3JHStA6C-UNQvqx7Zu9nMQdlR7YBezblYi2wpPAVQVp9bLBcFEi4nMSUKMEXYdYotpqaRKcX2_qXi0Mw1PatRzxHNsOsH_DuJkC4Exc0pm9WCsUktP2ew&__tn__=R%5D-R" rel="noopener" target="_blank">&ldquo;Todos deber&iacute;an volver a Nicaragua y no sufrir humillaciones hasta morir con dignidad&rdquo;,&nbsp;</a>se le&iacute;a en uno de los perfiles. &ldquo;Es una carga social muy alta que va a colapsar todo el sistema costarricense. Muy bonita la nota (period&iacute;stica), pero soy poco rom&aacute;ntica con respecto al futuro, <a href="https://www.facebook.com/vozdeguanacaste/posts/1882219198528066?comment_id=1882262991857020" rel="noopener" target="_blank">especialmente de la invasi&oacute;n que puedan hacer en la provincia (de Guanacaste)</a>&rdquo;, dec&iacute;a una persona desde otra cuenta.&nbsp;</p>
        <figure>
            <img src="https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2020-Febrero-Mama-Africa-migrantes-africanos-nicaraguenses-CLIP-Cesar-Arroyo-12.jpg" alt="" width="2000" height="1333" srcset="https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2020-Febrero-Mama-Africa-migrantes-africanos-nicaraguenses-CLIP-Cesar-Arroyo-12.jpg 2000w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2020-Febrero-Mama-Africa-migrantes-africanos-nicaraguenses-CLIP-Cesar-Arroyo-12-300x200.jpg 300w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2020-Febrero-Mama-Africa-migrantes-africanos-nicaraguenses-CLIP-Cesar-Arroyo-12-1024x682.jpg 1024w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2020-Febrero-Mama-Africa-migrantes-africanos-nicaraguenses-CLIP-Cesar-Arroyo-12-768x512.jpg 768w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2020-Febrero-Mama-Africa-migrantes-africanos-nicaraguenses-CLIP-Cesar-Arroyo-12-1536x1024.jpg 1536w" sizes="(max-width: 2000px) 100vw, 2000px" />
            <figcaption>Febrero de 2020, La Cruz, Guanacaste. Cientos de migrantes africanos y asi&aacute;ticos cruzan anualmente desde Costa Rica hacia Nicaragua por &laquo;el callej&oacute;n&raquo; hacia Nicaragua. Es un camino que separa a ambos pa&iacute;ses por un alambre de p&uacute;as. Cuando cruzan, al otro lado los intercepta el Ej&eacute;rcito de Nicaragua, que los lleva a la Direcci&oacute;n General de Migraci&oacute;n y les cobra $150 de salvoconducto. Foto: C&eacute;sar Arroyo Castro</figcaption>
        </figure>
        <h2><strong>La xenofobia muta seg&uacute;n el contexto</strong></h2>
        <p>Larissa Trist&aacute;n es docente de la Escuela de Ciencias de la Comunicaci&oacute;n Colectiva e investigadora del Centro de Investigaci&oacute;n en Comunicaci&oacute;n (CICOM) de la Universidad de Costa Rica. Junto a otros colegas realiz&oacute; un an&aacute;lisis sobre el comportamiento de los comentarios xenof&oacute;bicos durante la pandemia de covid-19 en el 2020 y parte del a&ntilde;o 2021. &nbsp;</p>
        <p>Las redes sociales se inundaron de noticias falsas relacionadas con los nicarag&uuml;enses, entre los que Trist&aacute;n identific&oacute;, por ejemplo, teor&iacute;as conspirativas que &ldquo;revelaban&rdquo; un convenio secreto entre la dictadura de Daniel Ortega en Nicaragua y del presidente costarricense Carlos Alvarado, para llevar nicarag&uuml;enses a atenderse en hospitales ticos.</p>
        <p>&ldquo;Se hac&iacute;an fotomontajes de nicarag&uuml;enses entrando en la frontera y que ven&iacute;an a tratarse aqu&iacute;. Es decir, muchos de los estereotipos que ya exist&iacute;an desde antes de la pandemia se actualizaron y se les dio un giro para la pandemia, pero no necesariamente eran nuevos. Ese estereotipo de que el nicarag&uuml;ense viene a aprovecharse de la Caja, se le da una vuelta de tuerca y se actualiza para el tema de la pandemia&rdquo;, explica Trist&aacute;n.&nbsp;</p>
        <p>La investigadora dice que es dif&iacute;cil medir si el discurso xenof&oacute;bico contra nicarag&uuml;enses increment&oacute; durante la pandemia, pero s&iacute; se empezaron a ver comentarios que les atribu&iacute;an la responsabilidad de los contagios en Costa Rica, a pesar de que el <a href="https://www.ministeriodesalud.go.cr/index.php/centro-de-prensa/noticias/741-noticias-2020/1555-caso-confirmado-por-covid-19-en-costa-rica" rel="noopener" target="_blank">primer caso de covid-19 en el pa&iacute;s se detect&oacute; en una mujer estadounidense de 49 a&ntilde;os.&nbsp;</a></p>
        <p>Los se&ntilde;alamientos de propagar el virus alcanzaron incluso a los trabajadores del sector agr&iacute;cola costarricense quienes, seg&uacute;n explica Trist&aacute;n, no vinieron al pa&iacute;s infectados. Por el contrario, se contagiaron en territorio costarricense por la falta de medidas preventivas de las empresas donde laboraban.&nbsp;</p>
        <p>Los discursos de odio se fueron adaptando en la medida en que el tema de la pandemia se fue quedando en segundo plano para pasar a la vacunaci&oacute;n. &nbsp;Los mismos grupos de Facebook y p&aacute;ginas de antivacunas continuaron perpetu&aacute;ndolo. A pesar de que al inicio de la pandemia dec&iacute;an que los nicarag&uuml;enses ven&iacute;an a contagiar la enfermedad, tambi&eacute;n se quejaron m&aacute;s tarde de que se les aplicaran vacunas en territorio tico.&nbsp;</p>
        <blockquote>
            <p>Es como querer generar pol&eacute;mica y conflictos sin ning&uacute;n sentido y durante la vacunaci&oacute;n s&iacute; hubo un repunte del discurso xenof&oacute;bico&rdquo;, agrega Trist&aacute;n.&nbsp;</p>
        </blockquote>
        <p>No sucede &uacute;nicamente en contra de nicarag&uuml;enses. Como ejemplo, Trist&aacute;n cuenta que en agosto de 2021 Costa Rica ofreci&oacute; refugio a 48 mujeres afganas que buscaban huir del Talib&aacute;n en Afganist&aacute;n, luego que Estados Unidos decidiera retirar sus tropas del pa&iacute;s. Entonces la &ldquo;preocupaci&oacute;n&rdquo; de los mismos grupos era que esas mujeres llegar&iacute;an a tener beb&eacute;s a Costa Rica o que incrementar&iacute;a la delincuencia.&nbsp;</p>
        <h2><strong>El perfil de los xenof&oacute;bicos</strong></h2>
        <p>Trist&aacute;n asegura que quienes esparcen los discursos xenof&oacute;bicos en redes sociales son &ldquo;personas comunes y corrientes&rdquo;, a veces amparados en el anonimato que facilitan las redes sociales, cuentas falsas o grupos muy espec&iacute;ficos, como por ejemplo Liberales Costa Rica, una p&aacute;gina que comparte con frecuencia discursos en contra de los migrantes nicarag&uuml;enses.&nbsp;</p>
        <p>Alberto cree que el ser de piel morena y su acento lo hizo f&aacute;cilmente identificable como nicarag&uuml;ense para el hombre blanco que decidi&oacute; atacarlo en el bar, quien adem&aacute;s se identific&oacute; como ac&oacute;lito del neonazismo, un movimiento que surgi&oacute; despu&eacute;s de la segunda guerra mundial y que busca reinstalar el nazismo en el mundo, amparado en la creencia de que existe una supremac&iacute;a blanca.&nbsp;</p>
        <p>El ataque contra el nicarag&uuml;ense no qued&oacute; en la calle frente a aquel bar de Guadalupe. Alberto no sabe explicar c&oacute;mo aquel hombre logr&oacute; ubicarlo en la casa donde &eacute;l viv&iacute;a en ese entonces. Lleg&oacute; a buscarlo acompa&ntilde;ado de otras personas y, cuando se dieron cuenta de que en la casa viv&iacute;an solo nicarag&uuml;enses, empezaron a escupir en el suelo diciendo: &ldquo;Qu&eacute; asco nicarag&uuml;enses&rdquo;, seg&uacute;n el relato de Alberto, quien cree que el agresor le tom&oacute; una fotograf&iacute;a mientras estaban en el bar y con ella ubic&oacute; su lugar de residencia.&nbsp;</p>
        <p>Desde entonces tuvo que mudarse de casa. Viv&iacute;a con el miedo de que en alg&uacute;n momento lo pudieran localizar otra vez, por lo que tuvo que buscar ayuda psicol&oacute;gica. &ldquo;En un momento estuve hablando con un psic&oacute;logo, es demasiado pesado, porque se te olvida un poco el sentimiento de persecuci&oacute;n de alerta que uno trae de la protesta de 2018 (en Nicaragua), que si ves sirenas de polic&iacute;as y te asustaban, ya se me hab&iacute;a pasado y en ese momento se me volvi&oacute; a activar. Tambi&eacute;n sent&iacute;a cierto odio por esa persona, porque me preguntaba por qu&eacute; existen este tipo de personas, pero es algo que ya no cargo&rdquo;, relata el nicarag&uuml;ense.&nbsp;</p>
        <p>Alberto lleg&oacute; a Costa Rica tras participar en las protestas contra Ortega. No tiene muchas opciones para regresar. Por eso dice que solo trata de dejar atr&aacute;s el mal episodio con su agresor, a quien no denunci&oacute; ante las autoridades policiales costarricenses, porque sus amigos le dijeron que no iban a hacer nada por &eacute;l.&nbsp;</p>
        <figure>
            <img src="https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-47.jpg" alt="" width="1920" height="1280" srcset="https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-47.jpg 1920w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-47-300x200.jpg 300w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-47-1024x683.jpg 1024w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-47-768x512.jpg 768w, https://cdn.imghaste.com/vozdeguanacaste.com/wp-content/uploads/2022/03/2021-diciembre-Derechos-ninez-migrante-La-Cruz-Santa-Cecilia-Nicaragua-Cesar-Arroyo-47-1536x1024.jpg 1536w" sizes="(max-width: 1920px) 100vw, 1920px" />
            <figcaption>La polic&iacute;a costarricense intercepta una mujer que acaba de ingresar al pa&iacute;s por el sector de la frontera de Pe&ntilde;as Blancas conocido como El Muro. Diciembre de 2021, La Cruz, Guanacaste. Foto: C&eacute;sar Arroyo Castro</figcaption>
        </figure>
        <p>Sus opciones son muy cortas: o trata de ignorar y vivir con la xenofobia en Costa Rica o regresa a Nicaragua a enfrentar las c&aacute;rceles del r&eacute;gimen orteguista, implacables en contra de cualquier persona que identifiquen como opositor.</p>
        <p>En Nicaragua, cuestionar al r&eacute;gimen de Daniel Ortega es el equivalente a ser considerado un criminal. La Polic&iacute;a de Nicaragua acecha d&iacute;a y noche las casas de opositores y sus familiares. Por eso muchos huyen de ese pa&iacute;s, y viven con el temor constante de estar siendo perseguidos para terminar muertos o en la c&aacute;rcel.</p>
        <p>En San Jos&eacute;, la provincia donde m&aacute;s comentarios xenof&oacute;bicos se emitieron, seg&uacute;n el estudio de la ONU, personas como Juliana &nbsp;<a href="https://vozdeguanacaste.com/huida-en-reversa-regresar-y-callar-para-vivir-en-nicaragua/" rel="noopener" target="_blank">no pueden regresar a Nicaragua</a>, porque ella cree que corre peligro de ser encarcelada, como los m&aacute;s de 155 presos pol&iacute;ticos privados de su libertad por opinar en contra de Ortega y su r&eacute;gimen. En las &uacute;ltimas ocasiones cuando viaj&oacute; a Nicaragua, seg&uacute;n cuenta, fue perseguida por miembros del Ej&eacute;rcito de su pa&iacute;s. Ella cree que esto tiene que ver con sus comentarios en contra del r&eacute;gimen en redes sociales.&nbsp;</p>
        <blockquote>
            <p>Cuando se dio la pandemia nos trataban muy feo en las redes sociales, hasta de &lsquo;muertos de hambre&rsquo;. Siempre lo mir&eacute; y con m&aacute;s de una persona peleaba&rdquo;, recuerda Juliana.&nbsp;</p>
        </blockquote>
        <p>Las redes sociales, tanto Facebook como Twitter permiten que un comentario pueda ser reportado por considerarse racista o porque afecta a un sector espec&iacute;fico de la poblaci&oacute;n que est&aacute; siendo discriminada. Trist&aacute;n recomienda que todas las personas que se vean afectadas por estos mensajes de odio puedan utilizar las herramientas que las mismas plataformas facilitan para que se pueda limitar la expansi&oacute;n de este tipo de discursos.&nbsp;</p>
        <p>Alberto dice que ahora anda con cuidado en las calles, cuando mira personas que tienen el mismo perfil que el atacante de Guadalupe, prefiere no acercarse. &ldquo;Sent&iacute;a cierto odio por esa persona, me preguntaba por qu&eacute; existen este tipo de personas, pero en las sesiones con el psic&oacute;logo logr&eacute; quitarme esa molestia&rdquo;, concluye.</p>
      </div>
  )

  return (
      <div>
        <Head>
          <title>{title}</title>
          <meta name="description" content={description} />
          <meta property="og:image" content={featuredImage} />
          <meta property="og:locale" content="es_ES" />
          <meta property="og:type" content="article" />
        </Head>
        <main className="main-container">
          <ArticleComponent lang={'es'} title={title} featuredImage={featuredImage} body={BodyComponent} autor={autor} medio={medio} fotografia={fotografia} />
          <Header lang={'es'}/>
          <Footer/>
        </main>
      </div>
  );
}

