import Head from 'next/head';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ArticleComponent from '@/components/ArticleComponent';

export default function Honduras(props) {

  const title = 'El temor al secuestro no detiene el éxodo de un país atormentado';
  const description = 'Para entender el éxodo hondureño hay que revisar la historia de la última década de este país: un golpe de Estado, un país saqueado y pobre, y un narcoestado.';
  const featuredImage = '/banner-honduras.jpg'
  const autor = "Texto: Allan Bu";
  const fotografia = "Fotografía: Jorge Cabrera";
  const medio = '<a target="_blank" href="https://twitter.com/ContraC_HN">@ContraC_HN</a>';

  const BodyComponent = (
      <div>
        <p className='excerpt'>Para entender el éxodo hondureño hay que revisar la historia de la última década de este país: un golpe de Estado, un país saqueado y pobre, y un narcoestado.  En Lucerna, un pequeño pueblo fronterizo en el occidente de Honduras, un obrero puede ganar 36 dólares a la semana, pero en Estados Unidos puede conseguir hasta 22 veces más en ese mismo tiempo. Esta es una historia que se repite en el pueblo y en el país entero: ser secuestrado, golpeado, abandonado en el desierto para lograr el sueño de salir de Honduras y vivir dignamente en un país ajeno. No hay miedo que valga con esos cálculos de sobrevivencia.</p>
        <h2><strong>1. Lucerna</strong></h2>
        <p>Lucerna es un peque&ntilde;o pueblo de Ocotepeque, ubicado en el occidente de Honduras, en la frontera con El Salvador y con Guatemala. Con polvorientas calles y modestas viviendas, esta localidad ha experimentado una migraci&oacute;n inusual en los &uacute;ltimos cuatro a&ntilde;os que ya muestra cambios en el pueblo: ahora contrastan con las casas antiguas campesinas unas viviendas grandes, con modernos dise&ntilde;os en los techos, amplios ventanales y fachadas parecidas a modelos construidos en suburbios estadounidenses.</p>
        <p>La mayor&iacute;a de estas viviendas fueron levantadas con dinero enviado por migrantes que dejaron su pueblo ante la falta de oportunidades para vivir dignamente. En ese pueblo, un jornalero que trabaja en la agricultura gana apenas unos 150 lempiras diarios (USD 7.00). Si trabaja toda la semana sumar&iacute;a 900 lempiras (USD 36.00), pero en Estados Unidos podr&iacute;a ganar entre 700 y 800 d&oacute;lares en el mismo per&iacute;odo. Por eso se van.</p>
        <p>Solamente en 2021, al menos unos 30 j&oacute;venes de Lucerna emprendieron viaje rumbo a Estados Unidos, seg&uacute;n los lugare&ntilde;os, y siete de esos migrantes fueron secuestrados en el norte de M&eacute;xico. Uno de los secuestrados fue Manuel, quien en enero del 2021 decidi&oacute; hacer una maleta y buscar una nueva vida en el pa&iacute;s del norte. En la aventura lo acompa&ntilde;aba su hijo de 17 a&ntilde;os. &laquo;A veces, uno por la falta de trabajo es que agarra esos caminos. Es complicado, uno quiere ver si hay algo all&aacute;&raquo;, dice.&nbsp;</p>
        <p>Con la llegada de la pandemia y la destrucci&oacute;n provocada por las tormentas tropicales Eta y Iota, el pa&iacute;s perdi&oacute; alrededor de medio mill&oacute;n de empleos, seg&uacute;n estimaciones del Consejo Hondure&ntilde;o de la Empresa Privada (Cohep).&nbsp;<a href="https://www.ine.gob.hn/V3/imag-doc/2021/11/cifras-de-pais-datos-2020.pdf"><strong>De acuerdo con cifras del Instituto Nacional de Estad&iacute;stica</strong></a> (INE), en el 2020 la Tasa de Desempleo Abierto alcanz&oacute; un 10.9%, el subempleo visible 27.3% y el empleo invisible 43%.&nbsp;</p>
    
        <figure>
            <img width="1500" height="1000" 
            src="https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937.jpg" alt="" 
            srcset="https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937.jpg 1500w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937-1024x683.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0937-768x512.jpg 768w" sizes="(max-width: 1500px) 100vw, 1500px" />
            <figcaption>Un hombre camina por una siembra de papaya luego del paso de dos huracanes ETA y IOTA en Progreso; Honduras. Foto Archivo CC/Jorge Cabrera</figcaption>
        </figure>

        <p>El 2020 fue un a&ntilde;o fat&iacute;dico para las Micro, Peque&ntilde;a y Mediana Empresas (Mipymes). Al menos 10% de estas tuvieron que cerrar operaciones indefinidamente por el confinamiento decretado por el gobierno para la contenci&oacute;n del Covid-19. Las Mipymes antes de la pandemia generaban hasta el 70% de los empleos en el pa&iacute;s.&nbsp;</p>
        <p>Para Honduras, el 2020 represent&oacute; un 10.9% de retroceso en su econom&iacute;a, seg&uacute;n estimaciones del Banco Central de Honduras (BCH). En el 2019, el INE estableci&oacute; que el porcentaje de pobreza en el pa&iacute;s era de 59%, en el a&ntilde;o 2020 esta instituci&oacute;n gubernamental no provey&oacute; informaci&oacute;n al respecto. Pero para el 2021, la encuesta aplicada por&nbsp;<a href="https://www.tunota.com/honduras-hoy/articulo/pobreza-en-honduras-incremento-en-un-73-6-tras-eta-iota-y-la-pandemia-del-covid-19-segun-estudio"><strong>el INE inform&oacute; que la pobreza alcanz&oacute; el 73.6%&nbsp;</strong></a>de los hogares hondure&ntilde;os.</p>
        <p>Manuel sali&oacute; del pa&iacute;s por esa pobreza, y con esfuerzo logr&oacute; pagar 8 mil d&oacute;lares a un coyote (traficante de personas) que los cruzar&iacute;a&nbsp;a &eacute;l y a su hijo por la frontera de Estados Unidos y M&eacute;xico. Manuel cuenta que en el camino el coyote les aconsej&oacute; entregarse a la Patrulla Fronteriza para hacer una solicitud de asilo, pero al pasar no tuvieron oportunidad de nada, casi inmediatamente fueron retornados a la ciudad fronteriza de Reynosa, en el estado de Tamaulipas.</p>
        <p>Quer&iacute;a cruzar nuevamente a Estados Unidos. Cuando ya estaba en M&eacute;xico recibi&oacute; una llamada del coyote, quien le dijo que lo iba a recoger en el puente de Reynosa que cruza el r&iacute;o Bravo, seg&uacute;n recuerda, pero instantes despu&eacute;s, cuando &eacute;l y su hijo salieron del sitio donde estaban resguardados, fueron secuestrados.</p>
        <p>&laquo;Los secuestradores tienen bien vigilados esos cruces de la frontera, est&aacute;n aliados los taxistas y hasta la misma polic&iacute;a&raquo;, asegura Manuel, quien tuvo que pagar otros cuatro mil d&oacute;lares para obtener su libertad y la de su hijo.&nbsp;<br /><br />Reynosa es la tercera ciudad en M&eacute;xico donde m&aacute;s se registraron secuestros de migrantes, seg&uacute;n estad&iacute;sticas de la organizaci&oacute;n sin fines de lucro Alto al Secuestro. Entre diciembre de 2018 y julio del 2021, se reportaron 49 secuestros, pero esta cifra no cuenta a los migrantes que no denunciaron ante las autoridades o que no contaron su historia a un medio de comunicaci&oacute;n. En el a&ntilde;o 2021,&nbsp;<a href="https://www.milenio.com/politica/comunidad/tamaulipas-secuestro-y-trafico-migrantes-estado-con-mayor-indice"><strong>la Unidad Antisecuestro de la Fiscal&iacute;a General de Tamaulipa</strong></a>s report&oacute; que hab&iacute;an liberado a 235 migrantes que se encontraban retenidos contra su voluntad en las localidades de Tamaulipas y Miguel Camargo.</p>
    
        <figure>
            <img width="2000" height="1335" src="https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972.jpg" alt="" srcset="https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972.jpg 2000w, https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972-1024x684.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972-768x513.jpg 768w, https://contracorriente.red/wp-content/uploads/2022/03/0942-_Z5A1972-1536x1025.jpg 1536w" sizes="(max-width: 2000px) 100vw, 2000px" />
            <figcaption>Migrantes que buscaban llegar a Estados Unidos, en su mayor&iacute;a hondure&ntilde;os y nicarag&uuml;enses, en una caravana que pretend&iacute;a llegar a Estados Unidos el 15 de enero de 2022. San Pedro Sula, Honduras. Aproximadamente 500 migrantes de Honduras y Nicaragua se reunieron en San Pedro Sula, Honduras, para formar una caravana con destino a Estados Unidos. Los migrantes huyen de la inseguridad y la falta de oportunidades de empleo en sus pa&iacute;ses. Foto Archivo CC/Jorge Cabrera</figcaption>
        </figure>
        
        <p>Manuel estuvo secuestrado durante tres d&iacute;as. Quienes lo privaron de libertad se hac&iacute;an llamar &laquo;Los Ma&ntilde;as&raquo;, seg&uacute;n lo que &eacute;l escuch&oacute;. El hondure&ntilde;o logr&oacute; contar que en ese momento hab&iacute;a m&aacute;s de 60 migrantes en la bodega donde los ten&iacute;an encerrados. Esa cifra de un solo d&iacute;a supera el regtro de denuncias que tiene la organizaci&oacute;n Alto al Secuestro en casi tres a&ntilde;os.&nbsp;</p>
        <p>Para pagar la suma que le pidieron llam&oacute; a su esposa en Honduras, pero ella no pudo enviar el dinero que ten&iacute;a que llegar por partes a M&eacute;xico, debido a las restricciones bancarias en ese pa&iacute;s. Un amigo que vive en Estados Unidos le prest&oacute; cuatro mil d&oacute;lares, dinero que Manuel tuvo que pagar una vez estuvo de regreso en Honduras.&nbsp;</p>
        <p>Recuerda que quienes lo raptaron no eran tipos tan violentos, pero estaban bien armados. &laquo;No golpearon a nadie, pero tampoco nos dejaban salir. Nos ten&iacute;an en un potrero y los oficiales de migraci&oacute;n llegaron a rescatarnos cuando ya casi todos hab&iacute;amos pagado&raquo;, cuenta Manuel.</p>
        <p>Despu&eacute;s de la experiencia, &eacute;l desconf&iacute;a del coyote que lo llev&oacute; hasta la frontera. &laquo;Es que me llam&oacute; que me ven&iacute;a a recoger para llevarme a una bodega y solo caminamos un poquito y nos entreg&oacute; a otros jodidos. En ese M&eacute;xico hay de todo&raquo;, dice Manuel desde su casa en Lucerna, la que construy&oacute; con adobe, un material muy utilizado en la zona rural del occidente de Honduras. Despu&eacute;s de lo ocurrido en M&eacute;xico, Manuel volvi&oacute; a trabajar en la agricultura.</p>
        <p>&laquo;Escuch&eacute; historias que la polic&iacute;a deten&iacute;a a gente que los coyotes ten&iacute;an escondidos esperando para cruzar, pero en lugar de deportarlos se los entregaban a los delincuentes. Es una sola mafia. La pasada de M&eacute;xico tal vez antes era m&aacute;s f&aacute;cil, pero ahora est&aacute; vergueado&raquo;, dice Manuel. A pesar de saber esto y del miedo, en septiembre de 2021 su hijo tom&oacute; nuevamente el camino rumbo a Estados Unidos. Esta vez logr&oacute; llegar y ya encontr&oacute; trabajo. &laquo;Casi lo secuestran otra vez, se salv&oacute; porque el coyote dividi&oacute; el grupo&raquo;, cuenta.</p>
    
        <blockquote>
            <p>&ldquo;Escuch&eacute; historias que la polic&iacute;a(en M&eacute;xico) deten&iacute;a a gente que los coyotes ten&iacute;an escondidos para cruzar, pero en lugar de deportarlos se los entregaban a los delincuentes. Es una sola mafia&rdquo;. Manuel</p>
            <footer><a href="https://twitter.com/intent/tweet?text=%E2%80%9CEscuch%C3%A9+historias+que+la+polic%C3%ADa%28en+M%C3%A9xico%29+deten%C3%ADa+a+gente+que+los+coyotes+ten%C3%ADan+escondidos+para+cruzar%2C+pero+en+lugar+de+deportarlos+se+los+entregaban+a+los+delincuentes.+Es+una+sola+mafia%E2%80%9D.%0AManuel%0A&url=https%3A%2F%2Fcontracorriente.red%2F%2F2022%2F03%2F24%2Fel-temor-al-secuestro-no-detiene-el-exodo-de-un-pais-atormentado%2F&via=ContraC_HN" target="_blank">Tuit</a></footer>
        </blockquote>
        <h2><strong>2. Del campo bananero</strong></h2>
        <p>Los hijos de don Filiberto, un hombre de 57 a&ntilde;os, salieron del norte de Honduras el 9 de septiembre del 2021 con rumbo a Estados Unidos. Igual que a miles de sus compatriotas los sedujo la idea de un&nbsp;trabajo con mejores ingresos en aras del bienestar familiar, pero el sue&ntilde;o de los dos muchachos solo tard&oacute; un d&iacute;a en convertirse en pesadilla. El 10 de septiembre, los dos fueron secuestrados&nbsp;en el estado mexicano de Tabasco.</p>
        <p>Ese d&iacute;a, caminaban por una carretera estatal cuando elementos de la polic&iacute;a mexicana que se conduc&iacute;an en una patrulla se detuvieron y les dijeron que si no se apartaban del camino tendr&iacute;an que detenerlos, seg&uacute;n el relato del padre de los muchachos. Los asustados j&oacute;venes siguieron el consejo de la autoridad y cuando tomaron una vereda, esta los llev&oacute; directo al grupo criminal &ndash;no identificado&ndash; que los secuestr&oacute;.&nbsp;</p>
        <p>El 11 de septiembre, despu&eacute;s de 24 horas de estar secuestrados, los delincuentes llamaron a don Filiberto para solicitar el rescate que rondaba los 200 mil lempiras ($10,000). &Eacute;l recuerda muy bien aquella llamada: &laquo;Yo les dije: &acute;pisto no tengo&acute;&raquo;, cuenta. Los secuestradores enviaron un video en el cual los dos muchachos eran brutalmente golpeados. &laquo;Ahora terminalos&raquo;, le dijo el padre a un hombre que lo llam&oacute; para preguntar por el rescate. &laquo;&iquest;Eso quer&eacute;s?, pues ma&ntilde;ana los matamos&raquo;, le respondieron.</p>
        <p>En los primeros seis meses del 2020, al menos 3, 250 personas migrantes sufrieron agresiones como secuestros, violaciones, asalto a mano armada y trata de blancas mientras esperaban que se resuelvan las solicitudes de asilo en la frontera de M&eacute;xico con Estados Unidos, de acuerdo con informaci&oacute;n recolectada por la organizaci&oacute;n internacional Human Rights First (HRF).</p>
        <p>La organizaci&oacute;n Al Otro Lado, que trabaja con migrantes en la ciudad de Tijuana en M&eacute;xico, fue consultada en esta investigaci&oacute;n sobre el registro de secuestros en la frontera. V&iacute;a email respondieron que no ten&iacute;an una cifra espec&iacute;fica de hondure&ntilde;os que hab&iacute;an sido raptados, pero que&nbsp;el 83 % de 20,000 migrantes de diferente&nbsp;nacionalidad encuestados report&oacute; haber sido v&iacute;ctima de alguna forma de violencia.</p>
        <p>Los migrantes sufren diversas agresiones en su ruta al norte, la m&aacute;s visible y medi&aacute;tica de todas es el secuestro, que se ha convertido en un negocio que genera miles de millones de d&oacute;lares, seg&uacute;n Rub&eacute;n Figueroa, activista del Movimiento Migrante Mesoamericano (MMM).</p>
        <p>Para Figueroa, el fen&oacute;meno no se puede entender sin la colaboraci&oacute;n de las autoridades. &laquo;No solamente hablamos de soborno, sino de una participaci&oacute;n directa en tr&aacute;fico de personas&raquo;, afirma. Esta consideraci&oacute;n coincide con el testimonio de migrantes secuestrados que fueron consultados para esta investigaci&oacute;n.</p>
        <p>En el 2015,<a href="https://www.fundacionjusticia.org/wp-content/uploads/2015/08/Informe-Secuestro-Migrantes-CNDH-2009.pdf"><strong>un informe de la Fundaci&oacute;n para la Justicia y Estado Democr&aacute;tico de Derecho&nbsp;</strong></a> (FJEDD) logr&oacute; precisar la nacionalidad de 552 v&iacute;ctimas de secuestro: 372 hondure&ntilde;os, 101 salvadore&ntilde;os, 74 guatemaltecos y 5 nicarag&uuml;enses. Hubo otros 609 de los que solo se pudo constatar que eran centroamericanos. Entre los secuestrados tambi&eacute;n hab&iacute;a ecuatorianos, brasile&ntilde;os y peruanos. Ese mismo informe sostiene que el 55% de los migrantes fueron secuestrados en el sur de M&eacute;xico, un 11% en el norte, 1.2% en el centro y un 32% que no fue posible precisar en qu&eacute; lugar fueron apresados.&nbsp;</p>
        <p>El problema no es nuevo y tampoco desconocido. En agosto del 2010, la noticia del asesinato de 72 migrantes centroamericanos en San Fernando, Tamaulipas, puso en las primeras planas el secuestro de indocumentados y, de acuerdo con un informe de la Agencia de las Naciones Unidas para los Refugiados (Acnur), este hecho&nbsp;<a href="https://www.acnur.org/fileadmin/Documentos/Publicaciones/2014/9484.pdf"><strong>oblig&oacute; al gobierno de M&eacute;xico</strong></a> &laquo;a reconocer la magnitud de la problem&aacute;tica del secuestro a migrantes&raquo;.</p>
        <p>La masacre fue atribuida al C&aacute;rtel de Los Zetas, uno de los m&aacute;s sanguinarios del territorio azteca que se dedicaba al tr&aacute;fico de drogas, robo de combustible y extorsi&oacute;n, entre otros delitos. Actualmente quedan peque&ntilde;as c&eacute;lulas por todo el pa&iacute;s, que secuestran y arrancan miles de d&oacute;lares a migrantes, que en su mayor&iacute;a son pobres.&nbsp;</p>
        <p>Don Filiberto cuenta que vio con impotencia c&oacute;mo sus hijos eran golpeados brutalmente en un video que se viraliz&oacute; en las redes. Despu&eacute;s de ver la publicaci&oacute;n, &eacute;l discuti&oacute; con los secuestradores y la &uacute;ltima frase que escuch&oacute; fue: &laquo;Hoy te los matamos&raquo;.&nbsp;</p>
        <p>&laquo;A ellos Dios los libr&oacute;&raquo;, dice don Filiberto. Sus hijos le cuentan que fueron golpeados durante 10 horas y cuando se desmayaron, los secuestradores pretendieron desaparecer los cuerpos. &laquo;Ellos no perdieron el conocimiento y escucharon a los delincuentes decir: &acute;vamos a traer unas palas para enterrar estos perros. Ya no mandaron el pisto (dinero)&acute;&raquo;, relata el padre. Sus hijos le contaron que se levantaron y huyeron luego de que desaparecieron sus captores. Despu&eacute;s de caminar durante tres d&iacute;as, lograron llegar a una vivienda donde les brindaron ayuda, pero ese d&iacute;a un grupo de hombres lleg&oacute; preguntando por dos j&oacute;venes inmigrantes. La se&ntilde;ora que los ayud&oacute; dijo no haberlos visto y despu&eacute;s envi&oacute; a los muchachos en taxi a la ciudad de Palenque, siempre en Tabasco, donde fueron atendidos en un centro m&eacute;dico y estuvieron recuper&aacute;ndose durante 15 d&iacute;as en un lugar seguro.&nbsp;</p>
    
        <figure>
            <img width="2000" height="1335" src="https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935.jpg" alt="" srcset="https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935.jpg 2000w, https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935-1024x684.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935-768x513.jpg 768w, https://contracorriente.red/wp-content/uploads/2022/03/0938-_Z5A1935-1536x1025.jpg 1536w" sizes="(max-width: 2000px) 100vw, 2000px" />
            <figcaption>Una migrante camina con su hija en los hombros hacia la frontera hondure&ntilde;a en medio de una caravana que pretende llegar a Estados Unidos el 15 de enero de 2022. San Pedro Sula, Honduras. Foto Archivo CC/Jorge Cabrera</figcaption>
        </figure>

        <p>Don Filiberto considera que a sus hijos no los secuestr&oacute; ning&uacute;n cartel, sino ladrones de M&eacute;xico y Guatemala que se han reunido para delinquir: &laquo;Lo perro es que aunque manden el pisto, siempre los matan. Mis hijos cuentan que miraron en una ocasi&oacute;n que mandaron el pisto y mataron a la gente&raquo;, dice.&nbsp;</p>
        <p>La Comisi&oacute;n Nacional de B&uacute;squeda en M&eacute;xico, que tiene datos desde 1964, registra que en ese pa&iacute;s hay casi 100 mil personas desaparecidas. Entre septiembre de 2020 y julio de 2021, ese organismo<a href="https://www.animalpolitico.com/2021/10/casi-100-mil-desaparecidos-mexico-parte-culpa-estado-nyt/"><strong>indica que se denunciaron 6,453 casos</strong></a>. M&eacute;xico es un pa&iacute;s azotado por la violencia, que ha emprendido una guerra contra el narcotr&aacute;fico que, seg&uacute;n recoge el medio Animal Pol&iacute;tico, deja unos 30 mil muertos al a&ntilde;o.&nbsp;</p>
        <p>Para los hijos de don Filiberto, la pesadilla continu&oacute;. Al retomar fuerzas, volvieron al camino hacia Estados Unidos y lograron cruzar la frontera, pero fueron detenidos por la migraci&oacute;n estadounidense, que ten&iacute;an un pedido de la fiscal&iacute;a mexicana para regresar a los dos hondure&ntilde;os a ese pa&iacute;s. &laquo;Fueron golpeados otra vez porque los oficiales les preguntaban qu&eacute; hab&iacute;an hecho para que los anduvieran buscando&raquo;, asegura don Filiberto.&nbsp;</p>
        <p>Al trascender el caso en redes sociales, la fiscal&iacute;a mexicana actu&oacute; de oficio. Por eso fueron detenidos en la frontera y deportados a M&eacute;xico, no a Honduras. A los dos hermanos se les extendi&oacute; la visa humanitaria e iniciaron el proceso de petici&oacute;n de asilo en Estados Unidos.&nbsp;</p>
        <p>Javier Mart&iacute;nez, trabajador de la Casa del Migrante en Saltillo, Coahuila, afirma que la respuesta de las autoridades mexicanas en los delitos contra migrantes es muy mala y que, seg&uacute;n sus c&aacute;lculos, el 99% de estos casos queda impune. &laquo;En el trabajo que hacemos s&iacute; tenemos acceso a poner las denuncias y quejas de violaci&oacute;n a los derechos humanos, el problema es que nunca se aterriza, las denuncias nunca llegan a manos de un juez&raquo;, dice.&nbsp;</p>
        <p>&nbsp;Cree que los casos prosperan solo cuando la situaci&oacute;n se ha vuelto medi&aacute;tica. &laquo;Tendr&iacute;a que ser un caso muy medi&aacute;tico en el cual las autoridades est&aacute;n siendo observadas por medios de comunicaci&oacute;n o sociedad civil pero, de lo contrario, las cosas se quedan en investigaci&oacute;n&raquo;, refiere Mart&iacute;nez.</p>
        <p>Don Filiberto cuenta su historia y la de sus hijos desde su casa ubicada en uno de los ex campos bananeros en El Progreso, Yoro, en el norte de Honduras, el lugar que una vez fue el centro de operaciones de la &laquo;<em>banana republic</em>&raquo;, un t&eacute;rmino utilizado para describir a un pa&iacute;s pobre, corrupto, poco democr&aacute;tico, con exportaciones de bajo valor y que se mueve al ritmo de intereses extranjeros. Ah&iacute;, donde crecieron sus hijos, permanece la nostalgia de la bananera y, aunque ya no es igual, abundan todav&iacute;a las plantaciones de banano para exportaci&oacute;n acompa&ntilde;ados del nuevo monocultivo predominante: la palma africana. Abundan all&iacute; tambi&eacute;n las historias de los j&oacute;venes que se fueron porque no hubo desarrollo gracias a esas plantaciones.&nbsp;</p>
        <p><strong>3. Migraci&oacute;n: noticia de televisi&oacute;n</strong></p>
        <p>Al hijo de la profesora Aminta lo secuestraron Los Zetas. Eso cuenta ella. A este joven le toc&oacute; salir huyendo de Honduras luego de recibir una amenaza por parte de los pandilleros del barrio donde viv&iacute;a en San Pedro Sula, principal ciudad del norte del pa&iacute;s. En la b&uacute;squeda por salvar su vida, casi la pierde. Alejandro &mdash;as&iacute; llamaremos al hijo de la profesora&mdash; estuvo dos veces secuestrado, pero antes de que esto pasara estuvo a punto de morir en un contenedor que transportaba casi 200 migrantes.&nbsp;</p>
        <p>Como si fuese una pel&iacute;cula, la profesora pudo ver por la se&ntilde;al de un canal estadounidense el momento en que la polic&iacute;a abr&iacute;a el contenedor y algunos de los indocumentados ca&iacute;an casi desmayados, pero su hijo saltaba hacia un matorral y hu&iacute;a de la autoridad. Ese escape fue el comienzo de la pesadilla. &laquo;Ah&iacute; supe que estaba vivo&raquo;, cuenta la profesora</p>
        <p>Al avanzar sin la compa&ntilde;&iacute;a de un coyote, casi de inmediato Alejandro cay&oacute; en manos de los Zetas. La profesora, mientras estaba en la escuela impartiendo clases a sus alumnos, recibi&oacute; una llamada en la que le solicitaron aproximadamente 4,000 d&oacute;lares. &laquo;Tiene que darme tiempo&raquo;, dijo ella y, seg&uacute;n recuerda, le contestaron: &laquo;Tiempo no tiene, mu&eacute;vase y cuidado habla con la polic&iacute;a porque todo eso lo manejamos nosotros&raquo;.&nbsp;</p>
        <p>Rub&eacute;n Figueroa, del Movimiento Migrante Mesoamericano, analiza que actualmente los grupos delictivos est&aacute;n secuestrando sin discriminaci&oacute;n: &laquo;se secuestra parejo, pero mucho m&aacute;s a los m&aacute;s pobres&raquo;, dice. Figueroa hace referencia a que antes a los secuestrados se les hac&iacute;a una especie de investigaci&oacute;n y, si ten&iacute;an familiares en Estados Unidos, les exig&iacute;an dinero. &laquo;A los migrantes que no ten&iacute;an familiares en Estados Unidos se les liberaba despu&eacute;s de torturas y maltratos. &nbsp;Hoy los criminales intentan sacar agua hasta de una piedra&raquo;, sostiene. El activista promigrantes se&ntilde;ala que los m&aacute;s vulnerables son los indocumentados que no han pagado a un coyote.&nbsp;</p>
    
        <figure>
            <img width="2000" height="1335" src="https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737.jpg" alt="" srcset="https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737.jpg 2000w, https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737-1024x684.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737-768x513.jpg 768w, https://contracorriente.red/wp-content/uploads/2022/03/Z5A1737-1536x1025.jpg 1536w" sizes="(max-width: 2000px) 100vw, 2000px" />
            <figcaption>Los migrantes hacen una cola para recibir comida y ropa, mientras esperan formar una caravana que pretende llegar a Estados Unidos el 15 de enero de 2022. San Pedro Sula, Honduras. Foto Archivo CC/Jorge Cabrera</figcaption>
        </figure>

        <p>Claudia Pinto, coordinadora de la oficina de la FJEDD en Honduras, sostiene que desde que se empezaron a documentar los secuestros de migrantes en 2009, no han dejado de suceder, pero ahora son mucho m&aacute;s visibles. A&ntilde;ade que gran parte de las personas que se est&aacute;n saliendo del pa&iacute;s no tienen para pagar un traficante y esto los vuelve m&aacute;s vulnerables. &laquo;Suena feo decirlo, pero las personas que pagan un coyote est&aacute;n pagando cierta seguridad que no tienen las personas que van solas&raquo;, se&ntilde;ala.&nbsp;</p>
        <p>En los &uacute;ltimos cuatro a&ntilde;os, Honduras ha registrado un flujo migratorio sin precedentes, que tuvo su m&aacute;xima expresi&oacute;n en las caravanas organizadas en 2018, en las que se reunieron hasta 15 mil hondure&ntilde;os que caminaron juntos hasta la frontera sur de Estados Unidos. El &uacute;ltimo antecedente fue en enero 2021,<a href="https://contracorriente.red/2021/01/23/de-regreso-de-la-caravana-con-los-suenos-golpeados/"><strong>cuando unos siete mil hondure&ntilde;os quisieron cruzar territorio guatemalteco</strong></a>, pero fueron apaleados en ese pa&iacute;s. No obstante, ese es el flujo visible y extraordinario, lo cierto es que diariamente salen entre 300 y 500 hondure&ntilde;os por puntos fronterizos del pa&iacute;s, lo hacen sin registro y sin dejar huella.&nbsp;</p>
        <p>No hay una cifra exacta del &eacute;xodo, pero<a href="https://www.telemundo.com/noticias/noticias-telemundo/inmigracion/secuestradores-de-migrantes-envian-videos-terrorificos-a-los-familiare-rcna2416"><strong>&nbsp;seg&uacute;n el Servicio de Aduanas y Protecci&oacute;n Fronteriza de Estados Unidos</strong></a>, en el 2020 detuvieron a 40,091 hondure&ntilde;os intentando entrar de forma irregular a Estados Unidos y a septiembre del 2021, la cifra ascend&iacute;a a 98,554 detenciones de hondure&ntilde;os, m&aacute;s del doble que el a&ntilde;o anterior.&nbsp;</p>
        <p>Aminta, la profesora, explica que tuvo que agotar los ahorros que ten&iacute;a en el banco para pagar el rescate solicitado por los secuestradores de su hijo. El dinero fue enviado en cinco partes porque el banco no le permiti&oacute; enviarlo en una sola transacci&oacute;n. Despu&eacute;s de pagar, el mismo grupo delictivo se encarg&oacute; de que Alejandro y otros migrantes secuestrados llegaran a la frontera. Cuando le prestaban el tel&eacute;fono al joven, para comunicarse con ella, este le contaba algunos detalles. En una ocasi&oacute;n le cont&oacute; que los secuestradores lo pusieron a &eacute;l y a otros migrantes que permanec&iacute;an cautivos,&nbsp;a cavar un enorme agujero sin saber para qu&eacute;. &laquo;Aqu&iacute; no se pregunta, mam&aacute;. Los que pagamos estamos tranquilos, a quienes no lo hicieron no los hemos visto&raquo;, recuerda la profesora que le dijo su hijo.</p>
        <p>Una vez en la frontera de M&eacute;xico y Estados Unidos, Alejandro cay&oacute; en manos de otro grupo criminal que se hac&iacute;a llamar los &laquo;Escorpiones Negros&raquo;. Solo hab&iacute;a pasado poco m&aacute;s de un mes del secuestro anterior. Ahora el rescate costaba 5,000 mil d&oacute;lares.&nbsp;</p>
        <p>La profesora tuvo que solicitar varios pr&eacute;stamos y no pudo conseguir la suma solicitada de inmediato. Tard&oacute; unos doce d&iacute;as y en ese lapso su hijo fue torturado. Le hicieron una videollamada que mostraba a su hijo amarrado y a sus captores asando carne. Los delincuentes torturaron a Alejandro coloc&aacute;ndole el asador caliente.&nbsp;</p>
        <p>Tras pagar el rescate, el hijo de la profesora fue encontrado en territorio estadounidense y fue auxiliado por miembros de la patrulla fronteriza. Estaba gravemente golpeado, ten&iacute;a muy da&ntilde;ados los ri&ntilde;ones por las golpizas recibidas y fue trasladado a Houston, donde estuvo en un hospital casi dos meses. Al mejorar su condici&oacute;n de salud fue deportado. En Honduras necesit&oacute; un psic&oacute;logo para recuperar su salud mental.</p>
        <p>&laquo;En ese camino todo es dinero. Los carteles piensan que los migrantes llevan dinero y no les importa si llevan o no. Usted tiene que buscarlo&raquo;, dice la profesora.</p>
    
        <blockquote>
            <p>&ldquo;En ese camino todo es dinero. Los carteles piensa que los migrantes llevan dinero y no les importa si llevan o no. Usted tiene que buscarlo&rdquo;. Madre de un migrante secuestrado</p>
            <footer><a href="https://twitter.com/intent/tweet?text=%E2%80%9CEn+ese+camino+todo+es+dinero.+Los+carteles+piensa+que+los+migrantes+llevan+dinero+y+no+les+importa+si+llevan+o+no.+Usted+tiene+que+buscarlo%E2%80%9D.%0AMadre+de+un+migrante+secuestrado&url=https%3A%2F%2Fcontracorriente.red%2F%2F2022%2F03%2F24%2Fel-temor-al-secuestro-no-detiene-el-exodo-de-un-pais-atormentado%2F&via=ContraC_HN" target="_blank">Tuit</a></footer>
        </blockquote>

        <p>La desesperanza se impone. Tras el terror vivido luego de pasar por dos secuestros y muchos d&iacute;as llorando por los recuerdos, Alejandro, el hijo de la profesora, decidi&oacute; emprender nuevamente el camino a Estados Unidos. Esta vez lo logr&oacute; y se encuentra trabajando.</p>
        <p>Las noticias sobre el secuestro de migrantes abundan en los medios de comunicaci&oacute;n, pero parece que para los gobiernos involucrados este delito queda invisibilizado. Claudia Pinto, coordinadora en Honduras de la Fundaci&oacute;n para la Justicia, se&ntilde;ala que ella ha escuchado decir al presidente mexicano Manuel L&oacute;pez Obrador que en &laquo;M&eacute;xico no ha pasado nada&raquo;. Agrega que &laquo;eso es muy grave porque es evadir su responsabilidad como estado y tambi&eacute;n es grave el abandono de nuestras autoridades [en Honduras] porque no hacen nada por buscar la coordinaci&oacute;n entre pa&iacute;ses. Son estados con estructura y podr&iacute;an coordinar acciones de b&uacute;squeda y rescate, pero no sucede&raquo;.&nbsp;</p>
        <p>En Honduras tambi&eacute;n este delito est&aacute; invisibilizado. Para esta investigaci&oacute;n se realiz&oacute; una solicitud a la Canciller&iacute;a de la Rep&uacute;blica mediante la Ley de Acceso de Informaci&oacute;n P&uacute;blica para conocer las cifras de migrantes que han denunciado secuestros, pero como respuesta se recibi&oacute; que este registro estaba en la Secretar&iacute;a de Seguridad, que coordina con la Interpol. Se realiz&oacute; otra solicitud de informaci&oacute;n, que tampoco fue resuelta.&nbsp;</p>
        <p>Adem&aacute;s, se intent&oacute; contactar a la vicecanciller del gobierno anterior, Nelly Jerez, pero no respondi&oacute; a los mensajes que se le enviaron. Por &uacute;ltimo, se solicit&oacute; informaci&oacute;n de secuestros a hondure&ntilde;os en el Consulado de Honduras en Saltillo, M&eacute;xico. Desde esta oficina se limitaron a decir que ten&iacute;an prohibido dar cualquier informaci&oacute;n o entrevista.</p>
        <p><strong>4. &iquest;Se quedar&aacute;n a ver un cambio en Honduras?</strong></p>
        <p>El &eacute;xodo no se detiene. Organizaciones como la Pastoral de Movilidad Humana calculan que diariamente salen entre 300 y 500 hondure&ntilde;os, quienes prefieren irse de un pa&iacute;s sometido por la violencia, el crimen organizado, la corrupci&oacute;n y hasta el cambio clim&aacute;tico. Honduras tiene un promedio de 40 muertes por cada 100 mil habitantes asociadas a la violencia com&uacute;n, al crimen organizado y al narcotr&aacute;fico. Una tasa alta para un pa&iacute;s que no est&aacute; en guerra. Muchos barrios de las principales ciudades siguen bajo el dominio de maras y pandillas, aunque el gobierno anterior se ufanaba de su pol&iacute;tica de seguridad.</p>
        <p>Pero el narcotr&aacute;fico ha estado ligado a los &uacute;ltimos dos presidentes de Honduras. Tony Hern&aacute;ndez, hermano del expresidente Juan Orlando Hern&aacute;ndez, y Fabio Lobo, hijo del expresidente Porfirio Lobo, fueron condenados por narcotr&aacute;fico por la justicia estadounidense. El exmandatario Hern&aacute;ndez fue se&ntilde;alado de tener nexos con el narcotr&aacute;fico en los juicios contra su hermano y Giovanni Fuentes Ram&iacute;rez y ahora fue solicitado en extradici&oacute;n por Estados Unidos y est&aacute; detenido en las instalaciones de las Fuerzas Especiales de la Polic&iacute;a Nacional de Honduras. Un juez de sentencia ya concedi&oacute; la extradici&oacute;n, pero la defensa apel&oacute; ante la Corte Suprema de Justicia.&nbsp;</p>
    
        <figure>
            <img width="2560" height="1707" src="https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-scaled.jpg" alt="El ex presidente Juan Orlando Hernandez es presentado ante los medios luego de su captura en Tegucigalpa, Honduras." srcset="https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-scaled.jpg 2560w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-300x200.jpg 300w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-1024x683.jpg 1024w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-768x512.jpg 768w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-1536x1024.jpg 1536w, https://contracorriente.red/wp-content/uploads/2022/03/IMG-0941-2048x1365.jpg 2048w" sizes="(max-width: 2560px) 100vw, 2560px" />
            <figcaption>El ex presidente Juan Orlando Hernandez es presentado ante los medios luego de su captura en Tegucigalpa, Honduras. Foto CC/Jorge Cabrera</figcaption>
        </figure>

        <p>Los escenarios tr&aacute;gicos no terminan ah&iacute;. En junio del 2021, Ricardo Z&uacute;niga, funcionario principal del gobierno de Joe Biden para las relaciones con Guatemala, El Salvador y Honduras, afirm&oacute; que en Honduras la corrupci&oacute;n drena del Estado unos 3000 millones de d&oacute;lares al a&ntilde;o. Lo dijo despu&eacute;s de que el anterior gobierno realiz&oacute; una cuestionada compra de siete hospitales m&oacute;viles por 47 millones de d&oacute;lares. A consideraci&oacute;n del Consejo Nacional Anticorrupci&oacute;n, CNA, hubo una sobrevaloraci&oacute;n de 31 millones de d&oacute;lares en dicha compra.</p>
        <p>En las elecciones de noviembre de 2021, el Partido Nacional perdi&oacute; las elecciones despu&eacute;s de 12 a&ntilde;os en el gobierno y Xiomara Castro, del Partido Libertad y Refundaci&oacute;n (LIBRE), se convirti&oacute;, el 27 de enero del 2022, en la primera mujer en ostentar la presidencia de Honduras. Su triunfo fue celebrado por multitudes en las calles y llen&oacute; de esperanza a gran parte de la poblaci&oacute;n. En su primer discurso, luego de conocer el primer conteo de los votos el 28 de noviembre, Castro dijo que en su gobierno trabajar&iacute;an para que ning&uacute;n joven tenga que migrar m&aacute;s para sobrevivir. A pesar de las esperanzas que levanta su discurso en algunas personas, el &eacute;xodo contin&uacute;a.</p>
        <p>A pocos d&iacute;as de la toma de posesi&oacute;n de Castro, el 15 de enero del 2022, se organiz&oacute; una nueva caravana en la Gran Terminal de San Pedro Sula. Unas 600 personas caminaron hasta la frontera de Corinto, entre Guatemala y Honduras, la mayor&iacute;a eran hondure&ntilde;os, pero tambi&eacute;n iba un grueso grupo de nicarag&uuml;enses. En esa caravana iba Javier, un hondure&ntilde;o que tiene cuatro a&ntilde;os desempleado y es padre de dos hijas. &laquo;Sabemos que hubo cambio de gobierno, pero el pa&iacute;s est&aacute; enfermo y su recuperaci&oacute;n ser&aacute; lenta&raquo;, dijo.</p>
        <p>En Lucerna, el pueblo donde siete de los j&oacute;venes que migraron en 2021 fueron secuestrados, Fredy, un hombre de 42 a&ntilde;os, planifica salir rumbo a Estados Unidos. Lo har&aacute; este a&ntilde;o. &Eacute;l, al igual que los hijos de don Filiberto, Alejandro y Manuel, est&aacute; dispuesto a atravesar un camino asolado por la muerte para dejar atr&aacute;s las penurias de un pa&iacute;s atormentado.</p>
    </div>
  )

  return (
      <div>
        <Head>
          <title>{title}</title>
          <meta name="description" content={description} />
          <meta property="og:image" content={featuredImage} />
          <meta property="og:locale" content="es_ES" />
          <meta property="og:type" content="article" />
        </Head>
        <main className="main-container">
          <ArticleComponent lang={'es'} title={title} featuredImage={featuredImage} body={BodyComponent} autor={autor} medio={medio} fotografia={fotografia} />
          <Header lang={'es'}/>
          <Footer/>
        </main>
      </div>
  );
}

